/** @file ArdaRHITypes.h
 * Convenience umbrella for the categorized RHI value and resource definitions.
 */

#pragma once

#include "RHI/Config/ArdaRHIStatus.h"
#include "RHI/Interop/ArdaRHICudaResourceInfo.h"
#include "RHI/Interop/ArdaRHINativeResourceImports.h"
#include "RHI/Interop/ArdaRHINativeResourceTypes.h"
#include "RHI/Memory/ArdaRHIHeap.h"
#include "RHI/Memory/ArdaRHIMemoryTypes.h"
#include "RHI/Memory/ArdaRHITiling.h"
#include "RHI/Pipelines/ArdaRHIComputePipeline.h"
#include "RHI/Pipelines/ArdaRHIFixedFunctionStates.h"
#include "RHI/Pipelines/ArdaRHIGraphicsPipeline.h"
#include "RHI/Pipelines/ArdaRHIMeshletPipeline.h"
#include "RHI/Pipelines/ArdaRHIRayTracingPipeline.h"
#include "RHI/Pipelines/ArdaRHIWorkGraphPipeline.h"
#include "RHI/Resources/ArdaRHIAccelerationStructures.h"
#include "RHI/Resources/ArdaRHIBuffer.h"
#include "RHI/Resources/ArdaRHIColor.h"
#include "RHI/Resources/ArdaRHIFormat.h"
#include "RHI/Resources/ArdaRHIFramebuffer.h"
#include "RHI/Resources/ArdaRHIResource.h"
#include "RHI/Resources/ArdaRHIResourceCollection.h"
#include "RHI/Resources/ArdaRHISampler.h"
#include "RHI/Resources/ArdaRHISamplerFeedback.h"
#include "RHI/Resources/ArdaRHITexture.h"
#include "RHI/Resources/ArdaRHIViews.h"
#include "RHI/Scheduling/ArdaRHIDrawTypes.h"
#include "RHI/Scheduling/ArdaRHIGpuFence.h"
#include "RHI/Scheduling/ArdaRHIQueries.h"
#include "RHI/Scheduling/ArdaRHIQueueTypes.h"
#include "RHI/Scheduling/ArdaRHIResourceCopies.h"
#include "RHI/Scheduling/ArdaRHIResourceStates.h"
#include "RHI/Scheduling/ArdaRHITransitions.h"
#include "RHI/Shaders/ArdaRHIBindingLayout.h"
#include "RHI/Shaders/ArdaRHIBindingSet.h"
#include "RHI/Shaders/ArdaRHIDescriptorTable.h"
#include "RHI/Shaders/ArdaRHIInputLayout.h"
#include "RHI/Shaders/ArdaRHIShader.h"
#include "RHI/Shaders/ArdaRHIShaderBundle.h"
#include "RHI/Shaders/ArdaRHIShaderTable.h"
