// Documentation snapshot of Source/ArdaTests/Examples/CornellBox/Private/Nodes/ArdaCornellTraceNode.cpp.
// Generated by Scripts/Docs/SyncGraphNodeRecipes.py; edit the original.
#include "ArdaCornellBoxPch.h"
#include "Nodes/ArdaCornellTraceNode.h"
#include "ArdaCornellNodeInternal.h"

namespace arda
{
#define ARDA_CORNELL_RAY_PARAMETERS()                                                                                  \
	ARDA_BEGIN_SHADER_PARAMETER_STRUCT(FArdaParameters)                                                                \
		ARDA_SHADER_ACCELERATION_STRUCTURE(mScene, 0, 0, arda::EArdaRHIShaderStage::AllRayTracing)                     \
		ARDA_SHADER_BUFFER_SRV(mVertices, 1, 0, arda::EArdaRHIShaderStage::AllRayTracing)                              \
		ARDA_SHADER_BUFFER_SRV(mIndices, 2, 0, arda::EArdaRHIShaderStage::AllRayTracing)                               \
		ARDA_SHADER_BUFFER_SRV(mMaterials, 3, 0, arda::EArdaRHIShaderStage::AllRayTracing)                             \
		ARDA_SHADER_BUFFER_UAV(mSampleRadiance, 0, 0, arda::EArdaRHIShaderStage::AllRayTracing)                        \
		ARDA_SHADER_UNIFORM_BUFFER(mFrame, 0, 0, arda::EArdaRHIShaderStage::AllRayTracing)                             \
	ARDA_END_SHADER_PARAMETER_STRUCT()

	class FArdaCornellRayGenerationShader final : public arda::FArdaGlobalShader
	{
	public:
		ARDA_CORNELL_RAY_PARAMETERS()
		ARDA_DECLARE_GLOBAL_SHADER(FArdaCornellRayGenerationShader);
	};

	class FArdaCornellMissShader final : public arda::FArdaGlobalShader
	{
	public:
		ARDA_CORNELL_RAY_PARAMETERS()
		ARDA_DECLARE_GLOBAL_SHADER(FArdaCornellMissShader);
	};

	class FArdaCornellClosestHitShader final : public arda::FArdaGlobalShader
	{
	public:
		ARDA_CORNELL_RAY_PARAMETERS()
		ARDA_DECLARE_GLOBAL_SHADER(FArdaCornellClosestHitShader);
	};

#undef ARDA_CORNELL_RAY_PARAMETERS

	struct FArdaCornellTraceNode::FArdaState
	{
		FArdaRHIDeviceRef mDevice;
		FArdaGlobalShaderMap mShaderMap;
		eastl::vector<FArdaInductorPipelineContribution> mStages;
		eastl::shared_ptr<const FArdaInductorPipelineConfiguration> mConfiguration;

		FArdaRHIStatus Initialize()
		{
			// Load the node-owned shader types through the common device shader map.
			if (!mShaderMap.Initialize(mDevice))
			{
				return CornellShaderError(mShaderMap);
			}

			const auto* Shader0 = mShaderMap.Find(FArdaCornellRayGenerationShader::GetStaticType());
			if (!Shader0)
			{
				return CornellShaderError(mShaderMap);
			}
			mStages.push_back(CornellShaderStage(Shader0, "CornellRayGen"));
			const auto* Shader1 = mShaderMap.Find(FArdaCornellMissShader::GetStaticType());
			if (!Shader1)
			{
				return CornellShaderError(mShaderMap);
			}
			mStages.push_back(CornellShaderStage(Shader1, "CornellMiss"));
			const auto* Shader2 = mShaderMap.Find(FArdaCornellClosestHitShader::GetStaticType());
			if (!Shader2)
			{
				return CornellShaderError(mShaderMap);
			}
			mStages.push_back(CornellShaderStage(Shader2, "", "CornellHitGroup"));
			auto Ray = eastl::make_shared<FArdaInductorPipelineConfiguration>();
			Ray->mKind = EArdaPipelineStateKind::RayTracing;
			Ray->mRayTracing.mDesc.mMaxPayloadSize = 32;
			Ray->mRayTracing.mDesc.mMaxAttributeSize = 8;
			Ray->mRayTracing.mDesc.mMaxRecursionDepth = 1;
			mConfiguration = eastl::move(Ray);
			return {};
		}
	};

	ARDA_IMPLEMENT_GLOBAL_SHADER(FArdaCornellRayGenerationShader,
	    "/ArdaTests/CornellBox/CornellPathTracer.hlsl",
	    "CornellRayGen",
	    "CornellRayGen",
	    arda::EArdaRHIShaderStage::RayGeneration)
	ARDA_IMPLEMENT_GLOBAL_SHADER(FArdaCornellMissShader,
	    "/ArdaTests/CornellBox/CornellPathTracer.hlsl",
	    "CornellMiss",
	    "CornellMiss",
	    arda::EArdaRHIShaderStage::Miss)
	ARDA_IMPLEMENT_GLOBAL_SHADER(FArdaCornellClosestHitShader,
	    "/ArdaTests/CornellBox/CornellPathTracer.hlsl",
	    "CornellClosestHit",
	    "CornellClosestHit",
	    arda::EArdaRHIShaderStage::ClosestHit)

	FArdaRHIStatus FArdaCornellTraceNode::DeclareResources(FArdaDependencyResourceContext& C, FArdaParameters& P)
	{
		if (!P.mWidth || !P.mHeight || !P.mSamples || uint64_t(P.mWidth) * P.mHeight > UINT64_MAX / 16 / P.mSamples)
		{
			return FArdaRHIStatus::Error(EArdaRHIResult::InvalidArgument, "Invalid ray output extent.");
		}

		FArdaRHIBufferDesc D;
		D.mByteSize = uint64_t(P.mWidth) * P.mHeight * P.mSamples * 16;
		D.mStructureStride = 16;
		D.mUsage = EArdaRHIBufferUsage::Structured | EArdaRHIBufferUsage::ShaderResource |
		    EArdaRHIBufferUsage::UnorderedAccess;
		return C.Buffer(P.mRadiance, "Radiance", D);
	}

	FArdaDependencyNodeRequirements FArdaCornellTraceNode::GetRequirements(const FArdaParameters&)
	{
		FArdaDependencyNodeRequirements R;
		R.mFeatures.mbRequireRayTracingPipelines = true;
		R.mFeatures.mbRequireAccelerationStructures = true;
		R.mFeatures.mbRequirePersistentShaderTables = true;
		return R;
	}

	FArdaDependencyNodeMetadata FArdaCornellTraceNode::GetMetadata()
	{
		return {"cornell.trace", 1};
	}

	eastl::string FArdaCornellTraceNode::GetCanonicalKey(const FArdaParameters& P)
	{
		FArdaDependencyKeyBuilder Key;
		Key.Resource(P.mTlas);
		Key.Resource(P.mVertices);
		Key.Resource(P.mIndices);
		Key.Resource(P.mMaterials);
		Key.Resource(P.mRadiance);
		Key.Resource(P.mConstants);
		Key.Resource(P.mBlas);
		Key.Value(P.mWidth);
		Key.Value(P.mHeight);
		Key.Value(P.mSamples);
		Key.Value(P.mWorkspaceBytes);
		return Key.Build();
	}

	TArdaRHIResult<eastl::shared_ptr<const FArdaCornellTraceNode::FArdaState>> FArdaCornellTraceNode::Prepare(
	    FArdaRHIDeviceRef Device)
	{
		if (!Device)
		{
			return {{},
			    FArdaRHIStatus::Error(EArdaRHIResult::InvalidState, "This node requires an initialized device.")};
		}

		auto State = eastl::make_shared<FArdaState>();
		State->mDevice = eastl::move(Device);

		// Publish prepared state only after all node-owned setup succeeds.
		auto Status = State->Initialize();
		if (!Status)
		{
			return {{}, eastl::move(Status)};
		}

		return {eastl::move(State), {}};
	}

	FArdaDependencyNodeDesc FArdaCornellTraceNode::Describe(const FArdaParameters& P, const FArdaState& Prepared)
	{
		FArdaDependencyNodeDesc D;
		D.mWorkspaceBytes = P.mWorkspaceBytes;
		D.BindShader<FArdaCornellRayGenerationShader::FArdaParameters>({{"mScene", P.mTlas},
		    {"mVertices", P.mVertices},
		    {"mIndices", P.mIndices},
		    {"mMaterials", P.mMaterials},
		    {"mSampleRadiance", P.mRadiance},
		    {"mFrame", P.mConstants}});
		D.mAccesses = {{P.mBlas, EArdaDependencyAccess::Read, EArdaRHIResourceState::AccelStructRead}};

		D.mPipelineStages = Prepared.mStages;
		D.mPipelines = {{"default", 0, EArdaPipelineStateKind::RayTracing, {}, Prepared.mConfiguration}};

		return D;
	}

	FArdaRHIStatus FArdaCornellTraceNode::Record(FArdaDependencyExecutionContext& C,
	    const FArdaParameters& P,
	    const FArdaState&,
	    FArdaInstanceState&)
	{
		// Resolve the compiled ray pipeline and its graph-owned shader table for this execution.
		if (auto S = C.SetRayTracingState(); !S)
		{
			return S;
		}

		return C.GetCommands().DispatchRays(P.mWidth, P.mHeight, P.mSamples);
	}
}
