// Documentation snapshot of Source/ArdaTests/Examples/CornellBox/Public/Nodes/ArdaCornellTraceNode.h.
// Generated by Scripts/Docs/SyncGraphNodeRecipes.py; edit the original.
#pragma once
#include "ArdaCornellNodeParameters.h"

namespace arda
{
	/** Parameters owned by one Cornell Trace node instance. */
	struct FArdaCornellTraceParameters
	{
		/** Input scene top-level acceleration structure. */
		FArdaDependencyResourceHandle mTlas;
		/** Input vertex buffer. */
		FArdaDependencyResourceHandle mVertices;
		/** Input index buffer. */
		FArdaDependencyResourceHandle mIndices;
		/** Input material buffer. */
		FArdaDependencyResourceHandle mMaterials;
		/** Output sample radiance buffer; leave empty for graph allocation. */
		FArdaDependencyResourceHandle mRadiance;
		/** Input frame constant buffer. */
		FArdaDependencyResourceHandle mConstants;
		/** Input bottom-level acceleration structure referenced by the scene. */
		FArdaDependencyResourceHandle mBlas;
		/** Ray dispatch width in pixels. */
		uint32_t mWidth = 1;
		/** Ray dispatch height in pixels. */
		uint32_t mHeight = 1;
		/** Samples traced per pixel in this dispatch. */
		uint32_t mSamples = 1;
		/** Scratch memory reserved while recording this node. */
		uint64_t mWorkspaceBytes = 0;
	};

	class FArdaCornellTraceNode final
	    : public TArdaComputeDependencyNode<FArdaCornellTraceNode, FArdaCornellTraceParameters>
	{
	public:
		struct FArdaState;
		static FArdaDependencyNodeMetadata GetMetadata();
		/** Hardware admission is checked before output declaration or device preparation. */
		static FArdaDependencyNodeRequirements GetRequirements(const FArdaParameters& Parameters);
		static FArdaRHIStatus DeclareResources(FArdaDependencyResourceContext& C, FArdaParameters& P);
		static eastl::string GetCanonicalKey(const FArdaParameters& Parameters);
		static TArdaRHIResult<eastl::shared_ptr<const FArdaState>> Prepare(FArdaRHIDeviceRef Device);

		static FArdaDependencyNodeDesc Describe(const FArdaParameters& Parameters, const FArdaState& State);
		static FArdaRHIStatus Record(FArdaDependencyExecutionContext& Context,
		    const FArdaParameters& Parameters,
		    const FArdaState& State,
		    FArdaInstanceState& Instance);
	};
}
