// Documentation snapshot of Source/ArdaTests/Examples/CornellBox/Private/Nodes/ArdaCornellNodeInternal.h.
// Generated by Scripts/Docs/SyncGraphNodeRecipes.py; edit the original.
#pragma once
#include "Nodes/ArdaCornellBoxNodes.h"
#include "ShaderStructs/ArdaGlobalShaderMap.h"

namespace arda
{
	inline FArdaRHIStatus CornellShaderError(const FArdaGlobalShaderMap& Map)
	{
		const auto Diagnostics = Map.GetDiagnostics();
		return FArdaRHIStatus::Error(EArdaRHIResult::InvalidState,
		    Diagnostics.empty() ? "Cornell node shader initialization failed." : Diagnostics.back().mMessage.c_str());
	}

	inline FArdaInductorPipelineContribution CornellShaderStage(const FArdaGlobalShaderInstance* Shader,
	    const char* Export = "",
	    const char* HitGroup = "")
	{
		FArdaInductorPipelineContribution S;
		S.mShader = Shader->GetShader();
		S.mBindingLayouts = Shader->GetBindingLayouts();
		S.mExportName = Export;
		S.mHitGroupName = HitGroup;
		return S;
	}
}
