#!/usr/bin/env python3
"""Resolve authored Unreal explanations to the pinned source inventory and emit offline docs."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from UnrealGuideContent import FAQ, GROUPS, INVARIANTS, ROADMAP, SOURCES, STAGES, TYPE_ROWS


def load_js(path: Path, variable: str) -> dict:
    text = path.read_text(encoding="utf-8")
    prefix = f"window.{variable} = "
    if not text.startswith(prefix) or not text.endswith(";\n"):
        raise ValueError(f"Unexpected data wrapper: {path}")
    return json.loads(text[len(prefix):-2])


def build(engine: Path, output: Path) -> dict:
    catalog = load_js(output / "catalog.js", "UnrealCatalog")
    by_name = {}
    for node in catalog["types"]:
        by_name.setdefault(node["qualified"], []).append(node)
    types = []
    for row in TYPE_ROWS.strip().splitlines():
        name, group, role, implementation = row.split("|")
        candidates = by_name.get(name, [])
        headers = [node for node in candidates if node["path"].endswith(".h")]
        candidates = headers or candidates
        if len(candidates) != 1:
            raise ValueError(f"Expected one curated definition for {name}: {[(x['path'], x['line']) for x in candidates]}")
        types.append(dict(candidates[0], group=group, role=role, implementation=implementation))
    curated = {node["qualified"]: node for node in types}
    stages = []
    for definition in STAGES:
        item = dict(definition)
        sources = []
        for source_query in item.pop("sourceQueries"):
            alias, query, *pinned_line = source_query
            path = "Engine/Source/Runtime/" + SOURCES[alias]
            lines = (engine / path).read_text(encoding="utf-8-sig").splitlines()
            matches = [i + 1 for i, line in enumerate(lines) if query in line]
            if not matches:
                raise ValueError(f"Missing source anchor for {item['id']}: {path} / {query}")
            line = pinned_line[0] if pinned_line else matches[0]
            if line not in matches:
                raise ValueError(f"Moved pinned source anchor: {path}:{line} / {query}")
            sources.append(dict(path=path, line=line, label=query))
        item["sources"] = sources
        item["typeIds"] = [curated[name]["id"] for name in item["types"]]
        stages.append(item)
    stages.sort(key=lambda stage: stage["column"])
    ids = {stage["id"] for stage in stages}
    for item in stages:
        if not set(item["depends"]) <= ids:
            raise ValueError(f"Unknown dependency in {item['id']}")
    return dict(meta=catalog["meta"], groups=[dict(id=i, number=n, title=t, summary=s) for i, n, t, s in GROUPS],
        types=types, stages=stages, invariants=[dict(title=t, text=s) for t, s in INVARIANTS],
        roadmap=[dict(title=t, work=w, gate=g) for t, w, g in ROADMAP], faq=[dict(question=q, answer=a) for q, a in FAQ],
        lanes=[dict(id=i, label=l) for i, l in [("setup", "Scene & views"), ("geometry", "Geometry & surfaces"), ("caches", "Persistent lighting scene"), ("lighting", "Lighting & composition"), ("output", "Image & output")]],
        official=[dict(title="Lumen technical details", url="https://dev.epicgames.com/documentation/en-us/unreal-engine/lumen-technical-details-in-unreal-engine"),
                  dict(title="Nanite virtualized geometry", url="https://dev.epicgames.com/documentation/en-us/unreal-engine/nanite-virtualized-geometry-in-unreal-engine"),
                  dict(title="Mesh drawing pipeline", url="https://dev.epicgames.com/documentation/en-us/unreal-engine/mesh-drawing-pipeline-in-unreal-engine")])


def reference(data: dict) -> str:
    meta = data["meta"]
    lines = ["# Unreal rendering atlas — text reference", "", f"Source: Unreal Engine {meta['version']}, commit `{meta['commit']}`. Local checkout: `{meta['engineRoot']}`.", "",
        "Generated by `Scripts/Docs/BuildUnrealGuide.py` from authored explanations and verified source anchors. This contains the pipeline walkthrough and general resource reference. The actual component/proxy inheritance and their GPU storage associations are in [primitive-reference.md](primitive-reference.md). Source paths are relative to the Unreal checkout, with one-based line numbers pinned to that commit. Explanations paraphrase responsibilities; engine implementation bodies are not reproduced.", "",
        "## Scope and reading the diagrams", "", meta["scope"], "", f"The inventory contains {meta['declarations']:,} declarations in {meta['files']:,} files; {len(data['types'])} key types have authored explanations. Modules: {', '.join(meta['modules'])}.", "",
        "The interactive scene page has actual C++ inheritance trees rooted at UPrimitiveComponent and FPrimitiveSceneProxy. Every parent-child edge follows a uniquely resolved declared base, including across module/plugin boundaries. Filtering retains original ancestors. All bases, including multiple inheritance and external interfaces, remain in the inspector. GPU storage and component/proxy associations appear separately from inheritance. The class reference is a flat searchable inventory. The sections below group reference explanations by responsibility; those headings are not class hierarchy nodes.", "",
        "The pipeline describes desktop deferred rendering with Nanite, Lumen GI/reflections and VSM enabled by default. Hardware/software tracing, async availability, material/platform support and show flags change the path. Mobile, forward rendering, path tracing, editor-only passes, plugins and every experimental mode are outside the detailed walkthrough. Column spacing is explanatory, not a measured duration or guaranteed serial GPU order. Arrows show selected major prerequisites, not every RDG edge. Conditional prerequisites are skipped when their feature is off; conventional paths remain.", "",
        "## Cross-cutting contracts", ""]
    for item in data["invariants"]:
        lines.extend([f"### {item['title']}", "", item["text"], ""])
    lines.extend(["## General type reference by responsibility", ""])
    for group in data["groups"]:
        lines.extend([f"### {group['title']}", "", group["summary"], ""])
        for node in data["types"]:
            if node["group"] != group["id"]:
                continue
            lines.extend([f"#### {node['qualified']}", "", f"- Kind: {node['kind']}; module: {node['module']}.",
                "- Declared bases: " + (", ".join(f"`{base}`" for base in node["bases"]) or "none in the indexed declaration") + ".",
                f"- Role: {node['role']}", f"- Reimplementation responsibility: {node['implementation']}",
                f"- Source: `{node['path']}:{node['line']}`.", ""])
            for base in node["baseLinks"]:
                if base.get("conditions"):
                    lines.extend([f"Conditional base `{base['name']}`: {'; '.join(base['conditions'])}. This mixin is not enabled in every build.", ""])
    lines.extend(["## Deferred rendering stages", ""])
    for number, item in enumerate(data["stages"], 1):
        lines.extend([f"### {number:02d}. {item['title']} ({item['id']})", "", item["summary"], "",
            f"Lane: {item['lane']}; column: {item['column'] + 1}; requires: {', '.join(item['requires']) or 'baseline/conditional subfeatures'}; async-capable grouping: {item['asyncCapable']}.", "",
            "Major prerequisites: " + (", ".join(item["depends"]) or "frame inputs") + ".", ""])
        for key, title in [("inputs", "Inputs"), ("outputs", "Outputs"), ("steps", "How it works"), ("operations", "Operations to implement"), ("validation", "Correctness checks")]:
            lines.extend([f"**{title}**", ""] + [f"{i}. {text}" for i, text in enumerate(item[key], 1)] + [""])
        if item["caveat"]:
            lines.extend(["Configuration/order caveat: " + item["caveat"], ""])
        lines.extend(["Related types: " + ", ".join(item["types"]) + ".", "", "Source anchors:", ""])
        lines.extend([f"- `{source['path']}:{source['line']}` — `{source['label']}`" for source in item["sources"]] + [""])
    lines.extend(["## Reimplementation roadmap", "", "This is an inferred engineering plan, not an inventory of existing Ardashir features. Each gate is a proposed correctness criterion, not a claim that an Unreal-equivalent renderer has been implemented or benchmarked.", ""])
    for item in data["roadmap"]:
        lines.extend([f"### {item['title']}", "", item["work"], "", "Exit gate: " + item["gate"], ""])
    lines.extend(["## Questions and distinctions", ""])
    for item in data["faq"]:
        lines.extend([f"### {item['question']}", "", item["answer"], ""])
    lines.extend(["## Further official reading", ""])
    lines.extend([f"- [{item['title']}]({item['url']})" for item in data["official"]])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--engine-root", type=Path, default=Path("D:/UnrealEngine"))
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[2] / "Docs/Unreal")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = build(args.engine_root, args.output)
    outputs = {"guide.js": "window.UnrealGuide = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n", "reference.md": reference(data)}
    for filename, value in outputs.items():
        path = args.output / filename
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != value:
                raise SystemExit(f"Stale guide output: {path}")
        else:
            path.write_text(value, encoding="utf-8", newline="\n")
    print(f"Resolved {len(data['types'])} explained types and {len(data['stages'])} pipeline stages.")


if __name__ == "__main__":
    main()
