"""Refresh source excerpts shipped with the static graph tutorial; --check detects drift."""
from pathlib import Path
import argparse
import html
import re

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "Docs/ArdaRDG"
REFERENCES = [
    "Source/ArdaTests/Examples/PixelSort/PixelSortRenderer.cpp",
    "Source/ArdaTests/Examples/PixelSort/Public/Nodes/ArdaPixelSortSortNode.h",
    "Source/ArdaTests/Examples/PixelSort/Private/Nodes/ArdaPixelSortSortNode.cpp",
    "Source/ArdaTests/Examples/PixelSort/Public/Nodes/ArdaPixelSortOperand.h",
    "Source/ArdaTests/Examples/PixelSort/Public/Nodes/ArdaPixelSortNodeParameters.h",
    "Source/ArdaTests/Examples/PixelSort/Private/Nodes/ArdaPixelSortOperand.cpp",
    "Source/ArdaTests/Examples/PixelSort/Private/Nodes/ArdaPixelSortKernels.cu",
    "Source/ArdaTests/Examples/PixelSort/Private/Nodes/ArdaPixelSortNodeInternal.h",
    "Source/ArdaTests/Examples/CornellBox/Private/ArdaCornellBoxRenderer.cpp",
    "Source/ArdaTests/Examples/CornellBox/Public/Nodes/ArdaCornellTraceNode.h",
    "Source/ArdaTests/Examples/CornellBox/Private/Nodes/ArdaCornellTraceNode.cpp",
    "Source/ArdaTests/Examples/CornellBox/Public/Nodes/ArdaCornellNodeParameters.h",
    "Source/ArdaTests/Examples/CornellBox/Private/Nodes/ArdaCornellNodeInternal.h",
    "Source/ArdaTests/Examples/CornellBox/Private/ArdaCornellBoxPch.h",
    "Source/ArdaTests/Examples/CornellBox/Private/Nodes/Shaders/CornellPathTracer.hlsl",
    "Source/ArdaInfra/ArdaRenderGraph/Tests/ArdaInductorGpuTests.cpp",
]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {}
    for source in REFERENCES:
        p = ROOT / source
        outputs[DOCS / "Examples/Reference" / p.name] = (
            "// Documentation snapshot of " + source + ".\n"
            "// Generated by Scripts/Docs/SyncGraphNodeRecipes.py; edit the original.\n"
            + p.read_text(encoding="utf-8")
        )
    chapter = DOCS / "node-recipes.html"
    text = chapter.read_text(encoding="utf-8")
    for source in REFERENCES:
        text = text.replace("../../" + source, "Examples/Reference/" + Path(source).name)
    text = text.replace("compilation.html#pipeline-inference", "compilation.html#pipelines")
    sources = {p.name:p for p in (DOCS/"Examples/Nodes").glob("*Node.*") if p.suffix in (".h",".cpp")}
    sources.update({Path(p).name:ROOT/p for p in REFERENCES})
    def refresh(match):
        name = html.unescape(match[1])
        p = sources.get(name)
        if p is None:
            return match[0]
        return match[0].split("<pre><code>")[0] + "<pre><code>" + html.escape(
            p.read_text(encoding="utf-8").strip()
        ) + "</code></pre></details>"
    text = re.sub(r"<details><summary>([^<]+)</summary>.*?</details>", refresh, text, flags=re.S)
    outputs[chapter] = text
    stale = []
    for p, content in outputs.items():
        if not p.exists() or p.read_text(encoding="utf-8") != content:
            stale.append(str(p.relative_to(ROOT)))
            if not args.check:
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_text(content, encoding="utf-8")
    if args.check and stale:
        raise SystemExit("Stale graph recipe excerpts:\n" + "\n".join(stale))
    print("Graph tutorial excerpts are current." if args.check else "Graph tutorial excerpts refreshed.")

if __name__ == "__main__":
    main()
