"""Renderer-facing requirements inferred from Unreal source; not a public export ABI."""

R = "Engine/Source/Runtime/"


def item(title, text, fields, work, source=None, links=()):
    return dict(title=title, text=text, fields=fields, work=work, sourceQuery=source, links=links)


GEOMETRY = [
    ("static", "Triangle mesh", "Asset ID/revision; LODs; position/tangent/normal/UV/color layouts; index width and ranges; section-to-material slots; local bounds; winding and mirrored-transform policy.", "Export a cooked, available conventional render LOD. Preserve seams and section ranges; share geometry among placements. CPU access to cooked buffers is a cook/runtime policy, not guaranteed by possessing a UStaticMesh."),
    ("instances", "Instancing, HISM, foliage & grass", "Shared geometry ID; stable instance IDs; current/previous transforms; per-instance custom values; bounds; visibility/fade/LOD state; material overrides.", "Resolve HISM/foliage/grass into instance records. Do not reuse compact Unreal array indices as permanent IDs. Instance order can change after insert/remove/compaction."),
    ("nanite", "Nanite geometry", "Chosen fidelity mode; conventional fallback availability/error; or native cluster/page hierarchy, streaming mappings, raster/material bins and deformation inputs.", "For an initial independent renderer, explicitly request a usable fallback or offline converted mesh. Record the fidelity loss. Native Nanite data is a virtualized encoding requiring streaming, traversal and material integration; it is not an ordinary index buffer."),
    ("skinned", "Skeletal / skinned mesh", "Rest streams; bone-index/weight layout; section bone palette; bind/reference pose; current/previous pose or deformed streams; morph weights/deltas; cloth/deformer output; bounds.", "Choose whether Unreal supplies final deformed geometry or your renderer evaluates skin/morph/cloth/deformer behavior. Include material WPO separately. Use the same frame's deformation for raster, rays and velocity."),
    ("instanced-skinned", "Instanced skinned mesh", "Shared skinned geometry; per-instance transform/identity; animation/deformation association; previous state; conventional versus Nanite path.", "Preserve which pose/deformation source belongs to which instance. One shared mesh does not imply one shared pose. Query supported runtime representations explicitly."),
    ("spline", "Spline mesh", "Source mesh; spline endpoints/tangents, scales, roll, offsets and deformation parameters; current/previous deformation; bounds.", "Evaluate the spline deformation yourself or receive baked/deformed vertices. Exporting only the source static mesh loses the actual scene shape."),
    ("landscape", "Landscape terrain", "Section/grid transform; height/normal textures; layer weights, visibility holes and material layer mapping; LOD/neighbor stitching; runtime virtual texture dependencies.", "Implement heightfield sampling and layer shading, or tessellate/bake a declared terrain representation. Treat Nanite Landscape and landscape mesh proxies according to their selected geometry path."),
    ("dynamic", "Dynamic mesh / modeling tools", "Versioned vertex streams and section/subset indices; material slots; dirty ranges; current/previous geometry and bounds.", "Convert editable CPU topology into renderer streams. Update only changed chunks where possible; topology edits invalidate draw ranges and acceleration structures."),
    ("procedural", "Procedural / custom mesh / cable", "Generated positions, attributes, triangle sections and material slots; generation/revision token; deformation history.", "Read the generated rendered mesh, not only collision triangles or simulation particles. CustomMesh and cable use different producers but can normalize to triangle streams."),
    ("collection", "Geometry Collection", "Piece mesh ranges; piece-to-transform mapping; current/previous rigid transforms; hidden/fractured state; material sections; chosen Nanite/conventional representation.", "Export the visible fracture pieces and their current transforms. The collection physics hierarchy is source state, not the GPU geometry itself."),
    ("cache", "Geometry Cache", "Decoded sample streams, indices and sample time; interpolation/topology-change policy; paired/current/previous positions; section materials.", "Decode or request the evaluated sample at the snapshot time. Handle topology changes rather than assuming a fixed skeletal rest mesh."),
    ("niagara", "Niagara / Cascade effects", "Renderer kind; evaluated float/half/int attributes; ID mapping/count; material bindings; sprite axes, mesh references, ribbon connectivity, sorting and bounds.", "Decide whether Unreal continues simulation and supplies evaluated render data or you implement the simulation. Sprites, meshes, ribbons, lights, decals and volume renderers need different conversion handlers. A particle component is not a ready-made triangle mesh."),
    ("hair", "Groom / hair", "Active strand/card/mesh/Nanite LOD; point and curve attributes; root bindings/interpolation; current/previous deformation; material and culling data.", "Start with an explicitly selected card/mesh approximation if strand support is unavailable. Strand curves require geometry generation/intersection, specialized shading, transparency/visibility and shadowing."),
    ("volume", "Heterogeneous / sparse volume", "Volume transform and bounds; voxel attribute meaning and units; sparse page table/physical tiles or dense conversion; sample time; scattering/extinction/emission parameters.", "Sample the volume and integrate participating media, or report it unsupported. A bounding box rendered as an opaque surface is not an equivalent conversion."),
    ("water", "Water & virtual heightfield surfaces", "Tile/patch selection; source height/displacement textures and virtual mappings; material parameters; water body/depth/underwater information.", "Normalize generated surface geometry or reproduce tile selection/displacement. Water also needs a deliberate refraction, absorption, reflection and underwater-composition policy; controller components are not necessarily render geometry."),
    ("points", "Point clouds / points / lines", "Point/segment attributes, positions, widths/radii, colors; selected batches and bounds; point-versus-splat expansion policy.", "Choose raster expansion or analytic intersections. An asset called a point cloud does not guarantee PT_PointList draw topology. Debug helpers can be filtered explicitly."),
    ("paper", "Paper2D, billboards, text & widgets", "Evaluated sprite/glyph/tile or world-widget geometry; atlas/font/render-target textures; material, orientation and sorting policy.", "Preserve camera-facing and animation behavior or bake it at snapshot time. World-space widgets use surfaces and render targets; screen-space UI is a separate output-composition decision."),
    ("model", "BSP/model & plugin-defined geometry", "Rendered model surfaces or plugin-owned streams; material ranges; bounds; lifetime; source capability and revision.", "Use a producer registry for unknown primitive/proxy families. Require a supported geometry export, an explicit approximation, or a reported omission. Never silently treat an unknown primitive as a static mesh."),
]

SECTIONS = [
    dict(id="contract", title="Define the Unreal → renderer contract", summary="Extract semantic render data at a known frame boundary, then let your renderer own its scene and GPU realization.", items=[
        item("Choose the integration boundary", "Two useful modes are an in-process Unreal adapter consuming render-thread snapshots/resources, or an exported/copied engine-neutral scene. The required semantic records are similar; resource access, shader reuse and synchronization differ.",
            ["Producer/version and Unreal revision; feature/platform settings; snapshot time; stable scene/asset/object IDs; supported capability manifest.", "For copied export: bytes/formats and dependencies. For borrowed GPU resources: device identity, lifetime lease, view/subresource range, ready/completion fences and state/queue handoff."],
            ["Implement extraction inside Unreal for live/cooked scenes; a .umap plus .uasset filenames is not a universal decoded scene format.", "A borrowed Unreal texture or FRHIBuffer does not make Unreal material shaders compatible with your shader ABI. Device sharing and material execution are separate contracts.", "Keep the producer adapter distinct from the renderer's own database. The existing ArdaScene plan describes immutable semantic snapshots; this page is an integration requirements guide, not a claim that the Unreal adapter already exists."], (R+"Engine/Public/SceneInterface.h", "class FSceneInterface")),
        item("Proposed record families", "These names are a suggested neutral schema, not Unreal class layouts or new implemented ArdaScene APIs.",
            ["SceneSnapshot: revision, time, world origin, active views, object records and capability/omission report.", "GeometryRecord + DeformationRecord: shared streams/topology and evaluated deformation inputs/results.", "PrimitiveRecord + InstanceRecord: placement, bounds, flags, section/material bindings and current/previous state.", "MaterialRecord + TextureRecord + SamplerRecord: executable or converted surface behavior and resource bindings.", "LightRecord + EnvironmentRecord + DecalRecord + VolumeRecord: illumination, media and non-mesh scene effects.", "ViewRecord + RenderSettings + UpdateBatch: camera/output/temporal state, feature choices and versioned changes."],
            ["Keep semantic fields independent from GPU packing, bindless indices, PSOs and acceleration-structure allocation.", "Separate shared assets from placements; represent section-level material bindings and instance overrides.", "Version every reference and retain dependencies until all consumers of a snapshot have finished."]),
        item("Coordinates, units & precision", "Convert coordinate conventions once at the adapter boundary and document the result.",
            ["Unreal world coordinates use left-handed, Z-up conventions and centimeters; asset/local coordinates and imported source axes still need their recorded transforms.", "World/local transforms, world-origin offset and high-precision positions; normal/tangent basis and handedness; triangle winding; negative/nonuniform scale.", "Current/previous world-to-view and projection matrices; translated-world origins; depth range/reversed-Z policy; viewport and exposure conventions."],
            ["Use a consistent large-world origin/high-precision strategy and camera-relative GPU coordinates. Do not cast large absolute world positions directly to float without a policy.", "Transform normals correctly under nonuniform scale and reconcile mirrored winding/culling. Test a known orientation/scale scene.", "Choose a canonical linear working color space and explicit physical-light/exposure conversion; numeric values alone do not guarantee visual equivalence."], (R+"Engine/Public/SceneView.h", "struct FViewMatrices"), links=[("Epic: coordinate system and spaces", "https://dev.epicgames.com/documentation/unreal-engine/coordinate-system-and-spaces-in-unreal-engine"), ("Epic: units of measurement", "https://dev.epicgames.com/documentation/en-us/unreal-engine/units-of-measurement-in-unreal-engine")]),
    ]),
    dict(id="geometry", title="Geometry representations you must recognize", summary="Each family needs an export/conversion handler. The first implementation may support a subset, but must report every approximation or omission.", items=[]),
    dict(id="materials", title="Materials are executable behavior", summary="A list of textures and a base color cannot reproduce arbitrary Unreal materials. Choose shader integration, graph translation, baking, or an explicitly limited material model.", items=[
        item("Material identity, bindings & evaluation", "Resolve UMaterialInterface/UMaterialInstance through their parent, static switches and runtime parameters, with per-section/per-instance overrides.",
            ["Material ID/revision; parent/static permutation key; domain; blend mode; shading-model set; two-sidedness, culling and depth/shadow policy.", "Scalar/vector/texture parameters, sampler state, parameter collections, per-primitive/per-instance custom data and time-dependent inputs.", "Vertex factory/deformation requirements; pass permutations; graph/custom-HLSL dependencies and material usage flags."],
            ["For shader reuse, satisfy Unreal's material/vertex-factory/pass bindings, uniform expressions, permutations and renderer services; compiled bytecode is not a portable shader contract.", "For translation, implement the selected graph operations and reject unsupported nodes. Resolve dynamic parameters at the correct snapshot time.", "For baking, state what is baked and at which view/time. WPO, scene-texture reads, refraction and arbitrary procedural/time/view-dependent effects cannot generally be preserved by a few baked maps."], (R+"Engine/Public/MaterialShared.h", "class FMaterial")),
        item("Surface parameters and special lobes", "Provide the inputs required by the selected shading model, not one fixed PBR tuple for every material.",
            ["Typical baseline: base color, metallic, roughness, specular, emissive, normal/tangent, opacity/mask and ambient occlusion.", "Special models can need subsurface color/profile, clear-coat amount/roughness/normal, anisotropy, hair/fiber parameters, cloth fuzz, eye refraction or water absorption/scattering.", "A material can select shading models through expressions. Substrate represents layered closures and material topology, not merely a rename of Default Lit."],
            ["Start with an agreed Default Lit/Unlit subset, plus Masked if needed; enumerate special-model conversion policies.", "Keep emissive radiance and baked/direct/indirect illumination distinct to avoid adding light twice.", "For Substrate, integrate compatible closure evaluation/storage or translate/bake a restricted subset and report the loss."], (R+"Engine/Classes/Engine/EngineTypes.h", "enum EMaterialShadingModel")),
        item("Coverage, deformation & transparency", "Depth, shadow, ray and color paths must agree about the material's geometry and coverage.",
            ["Opacity-mask threshold; two-sided normal policy; WPO/displacement inputs; pixel-depth offset; current/previous deformation.", "Blend equations and ordering; premultiplied versus straight alpha; refraction/distortion; depth testing/writes; translucency lighting mode; custom depth/stencil; render-after-DOF policy."],
            ["Apply mask/deformation consistently in depth, base, shadow and ray geometry. Compute conservative bounds for moved vertices.", "Implement transparent sorting/composition or a declared OIT method; do not route all translucent materials through the opaque GBuffer.", "Define how ray intersections handle alpha, two-sidedness and displaced/deformed surfaces. Record raster/trace representation mismatches."], (R+"Engine/Classes/Engine/EngineTypes.h", "enum EBlendMode")),
        item("Domains beyond mesh surfaces", "Surface, decal, light-function, volume, post-process and UI domains run at different places and have different inputs.",
            ["Material domain; required scene/depth/normal inputs; target/composition policy; projection volume or light association.", "For decals: transform, bounds, sort order, fade, affected channels, blend and receiver flags. For post-process materials: blend location and scene-texture dependencies."],
            ["Dispatch each domain to the appropriate renderer subsystem. A decal material is not just another mesh surface material.", "Treat editor/deprecated enum values explicitly rather than assuming every value represents a supported current path."], (R+"Engine/Public/MaterialDomain.h", "enum EMaterialDomain")),
    ]),
    dict(id="textures", title="Texture, buffer & sampler resources", summary="Transfer the actual format, interpretation, residency and access contract along with the data.", items=[
        item("Texture classes and layouts", "Recognize ordinary 2D images, arrays, cube/cube-array maps, volume textures, render targets, streamed/virtual textures and sparse-volume textures.",
            ["Dimensions, slices/faces/depth, mip count/resident range; pixel/block format; row/slice pitch; sRGB/linear interpretation and channel semantics.", "Normal-map packing, alpha meaning, compression/transcoding; sampler filter/address/mip bias/anisotropy; UV set or procedural coordinate source.", "Render-target producer and ready frame; virtual texture page tables/physical tiles and feedback, or an explicit resolved/baked representation."],
            ["Decode or directly support cooked formats for the target device; do not infer channels from filenames.", "Preserve mip/slice/subresource selection and streaming changes. A missing mip, default texture and unsupported texture type need separate diagnostics.", "Track dynamic render targets, video/UI/scene captures and virtual-texture dependencies as producers. Prevent cycles or define previous-frame reads."], (R+"Engine/Classes/Engine/Texture.h", "class UTexture")),
        item("CPU export versus GPU borrowing", "Unreal wrappers remain CPU objects. Their RHI handles reference allocations whose ownership, state and lifetime require an explicit integration contract.",
            ["Buffer element type/stride/count; byte offsets; index width; SRV/UAV interpretation; source revision and resident bytes.", "For external resources: compatible device/API, descriptor/view ownership, queue ownership/access state, synchronization, replacement and retirement notifications."],
            ["For a first renderer, prefer owned copies where feasible and let the renderer allocate its own resources. Readback is a synchronization/cost decision, not a zero-cost export.", "If resources are borrowed, wait for producers, declare accesses and return completion/state ownership; retain them across in-flight frames.", "Never serialize raw UObject, proxy, FRDG or RHI pointers as portable scene data."], (R+"RHI/Public/RHIResources.h", "class FRHIBuffer")),
    ]),
    dict(id="instances", title="Primitive placement, visibility & draw bindings", summary="A mesh asset alone does not identify what should appear in a view. Placements and sections carry essential rendering state.", items=[
        item("Primitive and instance records", "Represent one component's renderable contribution and any additional instances separately from shared geometry.",
            ["Stable ID/generation; geometry and deformation references; current/previous transform; world/local bounds; active LOD or LOD policy.", "Section-to-material mapping and overrides; per-instance/custom primitive data; visibility masks, hidden/owner-only flags, distance cull/fade and mobility.", "Cast/receive-shadow policy, lighting channels, custom depth/stencil, decal reception and ray-tracing visibility; negative-scale/culling state."],
            ["Evaluate visibility for the intended view and rendering mode; hidden in one view does not imply absent from shadows, reflections or other views.", "Maintain instance identity through compaction. Update bounds after deformation and invalidate only affected cached draws.", "Treat FMeshBatch/FMeshDrawCommand as render-thread submission descriptions, not a universal export format or a portable GPU mesh object."], (R+"Engine/Public/PrimitiveSceneProxy.h", "class FPrimitiveSceneProxy")),
        item("Draw and intersection descriptors", "Your renderer needs a normalized binding between a geometry range, material and instance, regardless of whether it rasterizes or traces rays.",
            ["Topology; vertex layout; index/base-vertex ranges; section/material ID; instance range; deformation/skin bindings; raster state.", "For ray consumers: geometry/instance mapping, opaque/alpha flags, hit-material lookup, transforms, build/update policy and lifetime."],
            ["Build your own PSO/draw/dispatch representation from the semantic scene. Decide which RHI topology forms to support or convert.", "Use conventional triangles, curves, procedural intersections or volume traversal deliberately; a scene primitive is not the same thing as a hardware primitive."], (R+"Engine/Public/MeshBatch.h", "struct FMeshBatch")),
    ]),
    dict(id="lighting", title="Lights, sky, captures & baked lighting", summary="Export light semantics and choose how illumination is evaluated. Dynamic, baked and cached contributions must not be counted twice.", items=[
        item("Directional, point, spot & rect lights", "Handle light shape and emission together with the settings that change which objects they illuminate.",
            ["Light ID/type; transform/direction; linear color, intensity and units; temperature conversion; attenuation radius/falloff.", "Spot inner/outer cones; rect size/orientation/barn doors/source texture; source radius/length; IES profile and light-function material.", "Mobility; lighting/view channels; shadow enable/bias/contact settings; volumetric/indirect contribution and ray-tracing policy."],
            ["Convert units/exposure consistently for each shape; do not use one point-light attenuation model for every light type.", "Choose shadow maps, ray shadows or another stated method; Unreal shadow resources are derived outputs, not required copies of scene input.", "Handle material light functions and IES as evaluated directional modulation or a documented approximation."], (R+"Engine/Public/LightSceneProxy.h", "class FLightSceneProxy")),
        item("Sky light, reflection captures & planar reflections", "Environment illumination and local reflection approximations are separate from finite local lights.",
            ["Sky capture/cubemap or real-time producer; rotation, intensity and convolution representation.", "Sphere/box reflection-capture transforms, influence extents, blend/brightness and captured cubemaps; planar reflection plane and view dependencies.", "Chosen diffuse GI and specular reflection methods and the conditions under which captures supplement/replace them."],
            ["Define a consistent environment-lighting and reflection blend policy. Avoid counting sky/capture radiance again on top of an already complete traced contribution.", "Re-render planar captures or explicitly omit/approximate them; a planar-reflection component is not just an ordinary environment cube."], (R+"Renderer/Private/ScenePrivate.h", "class FScene")),
        item("Lightmaps, shadowmaps & volumetric lightmaps", "Precomputed lighting is part of some scenes' intended appearance and may be absent or disabled in others.",
            ["Static mesh lightmap UV channel and scale/bias; lightmap/shadowmap textures and decode coefficients; per-primitive light-cache association.", "Volumetric-lightmap brick/indirection/sample data for movable objects where used; build validity and world transforms."],
            ["Choose to decode/import baked lighting or deliberately relight from source geometry/lights. Exporting only lights cannot reconstruct the exact baked result.", "Document which static/stationary contributions are already baked so the renderer does not add them again."], (R+"Engine/Public/LightMap.h", "class FLightMap")),
    ]),
    dict(id="environment", title="Atmosphere, media & non-mesh scene effects", summary="Scene appearance also depends on global and local media, surface projections and generated textures.", items=[
        item("Sky atmosphere, fog & clouds", "These are rendering inputs/systems, not ordinary primitive meshes.",
            ["Atmosphere planet/origin and Rayleigh/Mie/ozone settings; atmosphere lights; sky/aerial-perspective parameters.", "Exponential height fog, volumetric fog and local fog volume transforms/density/scattering; cloud layer bounds, density/material and lighting settings.", "Time-varying weather/material inputs, shadow interactions and history policy."],
            ["Implement LUT generation and participating-media integration, accept a declared baked/approximate sky, or flag unsupported media.", "Separate atmosphere inputs from generated LUTs, froxel grids and history buffers. The renderer can build its own derived representations.", "Compose fog, clouds, water and translucency according to depth and camera position; ordering changes appearance."], (R+"Renderer/Private/SkyAtmosphereRendering.cpp", "RenderSkyAtmosphereLookUpTables")),
        item("Decals, captures, volumes & output layers", "Register scene contributions that may not arrive as standard mesh component geometry.",
            ["Decal projection/material/channel state; heterogeneous and local volume records; scene-capture view/target dependencies.", "World-widget surfaces versus screen UI; post-process volumes and blend weights; water body/underwater state; optional debug/editor contributions."],
            ["Classify these producers before extracting only UPrimitiveComponent descendants. Lights, decals, camera and environment systems also enter the render scene.", "Resolve capture/update order and feedback loops. Emit a coverage report with producer/type and reason whenever a contribution is excluded."], (R+"Engine/Public/SceneInterface.h", "class FSceneInterface")),
    ]),
    dict(id="views", title="Views, temporal state & final image", summary="Geometry and materials cannot determine the final frame without camera, output and exposure settings.", items=[
        item("Camera and view family", "Capture the evaluated view used to render the scene, including any view extensions and camera/post-process blending you intend to support.",
            ["Projection mode, current/previous matrices, camera-relative origin, near/far/depth convention, frustum, view rectangle and render/output resolution.", "Temporal jitter, camera-cut flag, frame/sample time, stereo/multiview identity, show flags, visibility sets and per-view feature choices.", "Exposure/pre-exposure, working color space, white balance, tone curve/output transfer, bloom/DOF/motion blur and upscaler selection."],
            ["Keep separate histories for separate views; reset/reject history for camera cuts, resize, time jumps or incompatible method changes.", "Choose whether matching means scene-linear radiance, pre-exposed scene color or final display output; compare images at that same stage.", "Provide correct current/previous deformation and transforms for velocity, not only previous camera matrices."], (R+"Engine/Public/SceneView.h", "class FSceneView")),
    ]),
    dict(id="updates", title="Streaming, synchronization & scene updates", summary="The adapter must keep the same contracts true as the world changes; a one-time dump is only a static-scene mode.", items=[
        item("Versioned snapshot and change protocol", "Publish coherent immutable snapshots or ordered change batches at a defined scene/render boundary.",
            ["Add/update/remove events; monotonically interpreted revisions; asset residency/replacement; topology/material/deformation/transform dirty categories.", "World Partition/level streaming, world-origin changes, object destruction, asynchronous cooking/compilation readiness and resource leases.", "Frame provenance for animation, GPU effects and render targets; previous state and invalidation reasons."],
            ["Never read mutable game-thread objects from arbitrary render work. Copy/snapshot the needed values through supported thread boundaries.", "Remove or replace objects without leaving dangling material/geometry references; defer memory reclamation until queued GPU consumers complete.", "Changes to geometry/material/light state must invalidate relevant bounds, commands, acceleration structures and caches; a transform-only update is not enough for every change.", "Capture a snapshot plus capability report for reproducible comparisons and debugging."], (R+"Renderer/Private/SceneRendering.cpp", "IVisibilityTaskData* FSceneRenderer::OnRenderBegin")),
    ]),
    dict(id="fidelity", title="Decide what to reproduce, convert or rebuild", summary="Ingesting an Unreal scene and reproducing Unreal's image are different fidelity targets. Make the supported target explicit and measurable.", items=[
        item("Generated renderer data", "GPU Scene packing, Nanite visible work, BLAS/TLAS, Lumen cards/caches, VSM pages, GBuffer and temporal histories are renderer-specific representations.",
            ["Preserve source geometry/material/light/view semantics and the selected fallback assets.", "For any reused cache/native encoding: its revision, packing, shader consumers, update/invalidation rules, ownership and feature/build compatibility."],
            ["A conventional renderer can ingest the scene without reimplementing Nanite, Lumen or VSM if it provides declared alternatives and usable source/fallback data.", "For Unreal-like fidelity, implement the required geometry, BRDF, shadow/GI/reflection, media and temporal behaviors. Reusing a cache requires its full producer/consumer contract; copying one texture is insufficient.", "Do not export FRDG handles as persistent resources. Extract/import backing allocations only with an explicit lifetime contract."], (R+"Renderer/Private/GPUScene.h", "FGPUSceneResourceParameters")),
        item("Minimum useful implementation and acceptance suite", "Build a small coherent renderer first and expand coverage with named test scenes.",
            ["Baseline: indexed triangle meshes, instances, supported static/deformed geometry, opaque/masked Default Lit/Unlit materials, decoded textures/samplers, camera/exposure and supported lights.", "Coverage report: exact / converted / approximated / omitted / unavailable, with object ID, type, material feature and reason. These are proposed adapter statuses, not claims of existing support."],
            ["Test a textured mesh with multiple material sections; instancing with custom data; mirrored/nonuniform transforms; large-world coordinates; masks and two-sided foliage.", "Test skeletal/spline motion and camera cuts; dynamic material/texture changes; light unit/exposure consistency; streaming add/remove; resource replacement with multiple frames in flight.", "Use targeted scenes for transparency, hair, volumes, terrain, water, decals and baked lighting before claiming those features. Compare geometry/depth/normals/material outputs before final color.", "Then add native virtualized geometry, GI/reflections, scalable shadows and advanced temporal processing as required. The deferred-frame page gives operation-level work and source call sites."], (R+"Engine/Public/StaticMeshResources.h", "struct FStaticMeshLODResources")),
    ]),
]

ENUMS = [
    dict(name="EMaterialDomain", path=R+"Engine/Public/MaterialDomain.h", exclude=["MD_MAX"], note="Domain determines which subsystem executes the material. MD_RuntimeVirtualTexture is marked deprecated/hidden in this checkout."),
    dict(name="EBlendMode", path=R+"Engine/Classes/Engine/EngineTypes.h", exclude=["BLEND_MAX"], note="Opaque/Masked, translucent/additive/modulate, alpha composite/holdout and Substrate transmittance choices require different coverage/composition. Hidden aliases share values; they are not extra independent GPU blend equations."),
    dict(name="EMaterialShadingModel", path=R+"Engine/Classes/Engine/EngineTypes.h", exclude=["MSM_NUM", "MSM_MAX"], note="Includes Unlit/DefaultLit and specialized subsurface, coat, foliage, hair, cloth, eye, water and thin-translucent models. MSM_Strata is the hidden Substrate value; MSM_FromMaterialExpression selects via graph behavior."),
    dict(name="ETranslucencyLightingMode", path=R+"Engine/Classes/Engine/EngineTypes.h", exclude=["TLM_MAX"], note="Volumetric versus surface and per-vertex versus per-pixel lighting choices are separate from blend mode."),
    dict(name="EPrimitiveType", path=R+"RHI/Public/RHIDefinitions.h", exclude=["PT_Num", "PT_NumBits"], note="Hardware draw topology, not the scene's geometry family. Quad/rectangle modes require RHI capabilities; convert or reject unsupported topology explicitly."),
]
