#pragma once

#include "ArdaRenderGraphLog.h"
#include "ArdaRenderGraphResources.h"

#include <array>
#include <cstddef>
#include <functional>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

namespace arda::render_graph
{
    /** Identifies the semantic kind of a generated parameter-struct member. */
    enum class EARDGParameterType : uint8_t
    {
        /** An ordinary C++ value without graph resource semantics. */
        Value,

        /** A logical texture reference. */
        Texture,

        /** A logical buffer reference. */
        Buffer,

        /** A logical texture shader-resource view reference. */
        TextureShaderResourceView,

        /** A logical texture unordered-access view reference. */
        TextureUnorderedAccessView,

        /** A logical buffer shader-resource view reference. */
        BufferShaderResourceView,

        /** A logical buffer unordered-access view reference. */
        BufferUnorderedAccessView,

        /** A direct texture access with runtime state and subresource selection. */
        TextureAccess,

        /** A direct buffer access with runtime state and byte-range selection. */
        BufferAccess,

        /** A logical uniform-buffer reference. */
        UniformBuffer,

        /** An inline recursively enumerated parameter struct. */
        NestedStruct,

        /** Raster color and depth-stencil attachment declarations. */
        RenderTargetBindingSlots
    };

    /** Static description of one member generated by an ARDG parameter macro. */
    struct FARDGParameterMember
    {
        /** The source member name. */
        const char* mName = nullptr;

        /** The graph semantic represented by the member. */
        EARDGParameterType mType = EARDGParameterType::Value;

        /** The byte offset from the containing parameter object. */
        size_t mOffset = 0;

        /** The total byte size occupied by the member. */
        size_t mSize = 0;

        /** The C++ alignment required by the member. */
        size_t mAlignment = 1;

        /** The number of elements represented by this member. */
        size_t mElementCount = 1;

        /** The byte stride between elements. */
        size_t mElementStride = 0;

        /** The default NVRHI state implied by the member kind. */
        nvrhi::ResourceStates mDefaultState = nvrhi::ResourceStates::Unknown;

        /** Metadata for a nested parameter struct, or null for a leaf member. */
        const FARDGParameterMetadata* mNestedMetadata = nullptr;
    };

    /** A member resolved against a particular parameter-struct instance. */
    struct FARDGParameter
    {
        /** The static member description. */
        const FARDGParameterMember* mMember = nullptr;

        /** The address of the resolved member or array element. */
        const void* mValue = nullptr;

        /** The dotted member path, including array indices. */
        std::string mPath;

        /** The zero-based array index, or zero for a scalar member. */
        size_t mArrayIndex = 0;

        /** Returns the resolved member value as ValueType. */
        template <typename ValueType>
        [[nodiscard]] const ValueType& GetValue() const
        {
            if (mValue == nullptr)
            {
                ARDA_CHECK_MSG("A resolved render-graph parameter has no value.");
            }
            return *static_cast<const ValueType*>(mValue);
        }
    };

    /** Receives one resolved leaf or requested nested-container parameter. */
    using FARDGParameterVisitor = std::function<void(const FARDGParameter&)>;

    /** Immutable static metadata generated for an ARDG parameter struct. */
    class FARDGParameterMetadata final
    {
    public:
        /**
         * Constructs metadata for one C++ parameter struct.
         *
         * @param Name The C++ struct name.
         * @param Size The total C++ struct size.
         * @param Alignment The C++ struct alignment.
         * @param Members The generated member descriptions in declaration order.
         */
        FARDGParameterMetadata(
            const char* Name,
            size_t Size,
            size_t Alignment,
            std::vector<FARDGParameterMember> Members)
            : mName(Name)
            , mSize(Size)
            , mAlignment(Alignment)
            , mMembers(std::move(Members))
        {
            if (mName == nullptr || mSize == 0 || mAlignment == 0)
            {
                ARDA_CHECK_MSG("Invalid render-graph parameter metadata.");
            }

            for (const FARDGParameterMember& Member : mMembers)
            {
                if (Member.mName == nullptr ||
                    Member.mElementCount == 0 ||
                    Member.mElementStride == 0 ||
                    Member.mOffset > mSize ||
                    Member.mSize > mSize - Member.mOffset)
                {
                    ARDA_CHECK_MSG("Invalid render-graph parameter member metadata.");
                }

                if (Member.mType == EARDGParameterType::NestedStruct &&
                    Member.mNestedMetadata == nullptr)
                {
                    ARDA_CHECK_MSG("Nested render-graph parameter metadata is missing.");
                }
            }
        }

        /** Returns the C++ parameter-struct name. */
        [[nodiscard]] const char* GetName() const noexcept
        {
            return mName;
        }

        /** Returns the total C++ parameter-struct size. */
        [[nodiscard]] size_t GetSize() const noexcept
        {
            return mSize;
        }

        /** Returns the C++ parameter-struct alignment. */
        [[nodiscard]] size_t GetAlignment() const noexcept
        {
            return mAlignment;
        }

        /** Returns generated member descriptions in declaration order. */
        [[nodiscard]] const std::vector<FARDGParameterMember>& GetMembers() const noexcept
        {
            return mMembers;
        }

        /** Finds a direct member by source name, or returns null if it is absent. */
        [[nodiscard]] const FARDGParameterMember* FindMember(const std::string& Name) const noexcept
        {
            for (const FARDGParameterMember& Member : mMembers)
            {
                if (Name == Member.mName)
                {
                    return &Member;
                }
            }
            return nullptr;
        }

        /**
         * Enumerates resolved members in declaration order and recursively visits nested structs.
         *
         * @param Parameters A non-null instance described by this metadata.
         * @param Visitor The callback invoked for each resolved parameter.
         * @param bIncludeNestedContainers Whether nested struct containers are reported before their children.
         */
        void Enumerate(
            const void* Parameters,
            const FARDGParameterVisitor& Visitor,
            bool bIncludeNestedContainers = false) const
        {
            if (Parameters == nullptr)
            {
                ARDA_CHECK_MSG("Cannot enumerate a null render-graph parameter struct.");
            }
            if (!Visitor)
            {
                ARDA_CHECK_MSG("Cannot enumerate render-graph parameters without a visitor.");
            }

            EnumerateInternal(
                static_cast<const std::byte*>(Parameters),
                std::string(),
                Visitor,
                bIncludeNestedContainers);
        }

    private:
        void EnumerateInternal(
            const std::byte* Parameters,
            const std::string& Prefix,
            const FARDGParameterVisitor& Visitor,
            bool bIncludeNestedContainers) const
        {
            for (const FARDGParameterMember& Member : mMembers)
            {
                const std::string MemberPath =
                    Prefix.empty() ? Member.mName : Prefix + "." + Member.mName;

                for (size_t ElementIndex = 0; ElementIndex < Member.mElementCount; ++ElementIndex)
                {
                    const void* Value =
                        Parameters + Member.mOffset + ElementIndex * Member.mElementStride;
                    const std::string ElementPath =
                        Member.mElementCount == 1
                            ? MemberPath
                            : MemberPath + "[" + std::to_string(ElementIndex) + "]";

                    FARDGParameter Parameter;
                    Parameter.mMember = &Member;
                    Parameter.mValue = Value;
                    Parameter.mPath = ElementPath;
                    Parameter.mArrayIndex = ElementIndex;

                    if (Member.mType == EARDGParameterType::NestedStruct)
                    {
                        if (bIncludeNestedContainers)
                        {
                            Visitor(Parameter);
                        }
                        Member.mNestedMetadata->EnumerateInternal(
                            static_cast<const std::byte*>(Value),
                            ElementPath,
                            Visitor,
                            bIncludeNestedContainers);
                    }
                    else
                    {
                        Visitor(Parameter);
                    }
                }
            }
        }

        const char* mName = nullptr;
        size_t mSize = 0;
        size_t mAlignment = 0;
        std::vector<FARDGParameterMember> mMembers;
    };
}

#define ARDG_INTERNAL_PARAMETER(MemberKind, CppType, MemberName, DefaultState)                         \
        FARDGMemberId##MemberName;                                                                     \
    public:                                                                                             \
        CppType MemberName{};                                                                           \
    private:                                                                                            \
        struct FARDGNextMemberId##MemberName                                                            \
        {                                                                                                \
        };                                                                                               \
        static void FARDGAppendMembers(                                                                  \
            FARDGNextMemberId##MemberName,                                                               \
            std::vector<::arda::render_graph::FARDGParameterMember>& Members)                           \
        {                                                                                                \
            FARDGAppendMembers(FARDGMemberId##MemberName{}, Members);                                    \
            Members.push_back({                                                                          \
                #MemberName,                                                                              \
                MemberKind,                                                                               \
                offsetof(FARDGThisStruct, MemberName),                                                    \
                sizeof(CppType),                                                                          \
                alignof(CppType),                                                                         \
                1u,                                                                                       \
                sizeof(CppType),                                                                          \
                DefaultState,                                                                             \
                nullptr});                                                                                \
        }                                                                                                \
        typedef FARDGNextMemberId##MemberName

#define ARDG_INTERNAL_PARAMETER_ARRAY(MemberKind, CppType, MemberName, Count, DefaultState)            \
        FARDGMemberId##MemberName;                                                                       \
    public:                                                                                              \
        std::array<CppType, Count> MemberName{};                                                         \
    private:                                                                                             \
        struct FARDGNextMemberId##MemberName                                                             \
        {                                                                                                 \
        };                                                                                                \
        static void FARDGAppendMembers(                                                                   \
            FARDGNextMemberId##MemberName,                                                                \
            std::vector<::arda::render_graph::FARDGParameterMember>& Members)                            \
        {                                                                                                 \
            FARDGAppendMembers(FARDGMemberId##MemberName{}, Members);                                     \
            Members.push_back({                                                                           \
                #MemberName,                                                                               \
                MemberKind,                                                                                \
                offsetof(FARDGThisStruct, MemberName),                                                     \
                sizeof(std::array<CppType, Count>),                                                        \
                alignof(std::array<CppType, Count>),                                                       \
                Count,                                                                                     \
                sizeof(CppType),                                                                           \
                DefaultState,                                                                              \
                nullptr});                                                                                 \
        }                                                                                                 \
        typedef FARDGNextMemberId##MemberName

#define ARDG_INTERNAL_NESTED_PARAMETER(StructType, MemberName)                                           \
        FARDGMemberId##MemberName;                                                                        \
    public:                                                                                               \
        StructType MemberName{};                                                                          \
    private:                                                                                              \
        struct FARDGNextMemberId##MemberName                                                              \
        {                                                                                                  \
        };                                                                                                 \
        static void FARDGAppendMembers(                                                                    \
            FARDGNextMemberId##MemberName,                                                                 \
            std::vector<::arda::render_graph::FARDGParameterMember>& Members)                             \
        {                                                                                                  \
            FARDGAppendMembers(FARDGMemberId##MemberName{}, Members);                                      \
            Members.push_back({                                                                            \
                #MemberName,                                                                                \
                ::arda::render_graph::EARDGParameterType::NestedStruct,                                    \
                offsetof(FARDGThisStruct, MemberName),                                                      \
                sizeof(StructType),                                                                         \
                alignof(StructType),                                                                        \
                1u,                                                                                         \
                sizeof(StructType),                                                                         \
                nvrhi::ResourceStates::Unknown,                                                             \
                &StructType::GetStaticMetadata()});                                                         \
        }                                                                                                  \
        typedef FARDGNextMemberId##MemberName

#define ARDG_INTERNAL_NESTED_PARAMETER_ARRAY(StructType, MemberName, Count)                              \
        FARDGMemberId##MemberName;                                                                        \
    public:                                                                                               \
        std::array<StructType, Count> MemberName{};                                                       \
    private:                                                                                              \
        struct FARDGNextMemberId##MemberName                                                              \
        {                                                                                                  \
        };                                                                                                 \
        static void FARDGAppendMembers(                                                                    \
            FARDGNextMemberId##MemberName,                                                                 \
            std::vector<::arda::render_graph::FARDGParameterMember>& Members)                             \
        {                                                                                                  \
            FARDGAppendMembers(FARDGMemberId##MemberName{}, Members);                                      \
            Members.push_back({                                                                            \
                #MemberName,                                                                                \
                ::arda::render_graph::EARDGParameterType::NestedStruct,                                    \
                offsetof(FARDGThisStruct, MemberName),                                                      \
                sizeof(std::array<StructType, Count>),                                                       \
                alignof(std::array<StructType, Count>),                                                      \
                Count,                                                                                      \
                sizeof(StructType),                                                                         \
                nvrhi::ResourceStates::Unknown,                                                             \
                &StructType::GetStaticMetadata()});                                                         \
        }                                                                                                  \
        typedef FARDGNextMemberId##MemberName

/** Begins a UE-style render-graph parameter struct declaration. */
#define ARDG_BEGIN_PARAMETER_STRUCT(StructType)                                                           \
    struct StructType                                                                                      \
    {                                                                                                      \
    public:                                                                                                \
        StructType() = default;                                                                            \
    private:                                                                                               \
        using FARDGThisStruct = StructType;                                                                \
        static constexpr const char* FARDGStructName = #StructType;                                        \
        struct FARDGFirstMemberId                                                                          \
        {                                                                                                  \
        };                                                                                                 \
        static void FARDGAppendMembers(                                                                    \
            FARDGFirstMemberId,                                                                            \
            std::vector<::arda::render_graph::FARDGParameterMember>&)                                     \
        {                                                                                                  \
        }                                                                                                  \
        typedef FARDGFirstMemberId

/** Ends an ARDG parameter struct and exposes its immutable static metadata. */
#define ARDG_END_PARAMETER_STRUCT()                                                                        \
        FARDGLastMemberId;                                                                                 \
    public:                                                                                                \
        static const ::arda::render_graph::FARDGParameterMetadata& GetStaticMetadata()                    \
        {                                                                                                  \
            static_assert(std::is_standard_layout_v<FARDGThisStruct>,                                     \
                "ARDG parameter structs must use standard layout.");                                      \
            static const ::arda::render_graph::FARDGParameterMetadata Metadata = []                       \
            {                                                                                              \
                std::vector<::arda::render_graph::FARDGParameterMember> Members;                          \
                FARDGAppendMembers(FARDGLastMemberId{}, Members);                                          \
                return ::arda::render_graph::FARDGParameterMetadata(                                      \
                    FARDGStructName,                                                                        \
                    sizeof(FARDGThisStruct),                                                                \
                    alignof(FARDGThisStruct),                                                               \
                    std::move(Members));                                                                    \
            }();                                                                                           \
            return Metadata;                                                                               \
        }                                                                                                  \
    };

/** Declares an ordinary value member in an ARDG parameter struct. */
#define ARDG_PARAMETER(CppType, MemberName)                                                               \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::Value,                                                  \
        CppType,                                                                                           \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::Unknown)

/** Declares an array of ordinary value members in an ARDG parameter struct. */
#define ARDG_PARAMETER_ARRAY(CppType, MemberName, Count)                                                  \
    ARDG_INTERNAL_PARAMETER_ARRAY(                                                                         \
        ::arda::render_graph::EARDGParameterType::Value,                                                  \
        CppType,                                                                                           \
        MemberName,                                                                                        \
        Count,                                                                                             \
        nvrhi::ResourceStates::Unknown)

/** Declares a logical texture member with default shader-resource access. */
#define ARDG_TEXTURE(MemberName)                                                                           \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::Texture,                                                \
        ::arda::render_graph::FARDGTextureRef,                                                             \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::ShaderResource)

/** Declares an array of logical textures with default shader-resource access. */
#define ARDG_TEXTURE_ARRAY(MemberName, Count)                                                              \
    ARDG_INTERNAL_PARAMETER_ARRAY(                                                                         \
        ::arda::render_graph::EARDGParameterType::Texture,                                                \
        ::arda::render_graph::FARDGTextureRef,                                                             \
        MemberName,                                                                                        \
        Count,                                                                                             \
        nvrhi::ResourceStates::ShaderResource)

/** Declares a logical buffer member with default shader-resource access. */
#define ARDG_BUFFER(MemberName)                                                                            \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::Buffer,                                                 \
        ::arda::render_graph::FARDGBufferRef,                                                              \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::ShaderResource)

/** Declares an array of logical buffers with default shader-resource access. */
#define ARDG_BUFFER_ARRAY(MemberName, Count)                                                               \
    ARDG_INTERNAL_PARAMETER_ARRAY(                                                                         \
        ::arda::render_graph::EARDGParameterType::Buffer,                                                 \
        ::arda::render_graph::FARDGBufferRef,                                                              \
        MemberName,                                                                                        \
        Count,                                                                                             \
        nvrhi::ResourceStates::ShaderResource)

/** Declares a logical texture shader-resource view member. */
#define ARDG_TEXTURE_SRV(MemberName)                                                                       \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::TextureShaderResourceView,                              \
        ::arda::render_graph::FARDGTextureSRVRef,                                                          \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::ShaderResource)

/** Declares an array of logical texture shader-resource view members. */
#define ARDG_TEXTURE_SRV_ARRAY(MemberName, Count)                                                          \
    ARDG_INTERNAL_PARAMETER_ARRAY(                                                                         \
        ::arda::render_graph::EARDGParameterType::TextureShaderResourceView,                              \
        ::arda::render_graph::FARDGTextureSRVRef,                                                          \
        MemberName,                                                                                        \
        Count,                                                                                             \
        nvrhi::ResourceStates::ShaderResource)

/** Declares a logical texture unordered-access view member. */
#define ARDG_TEXTURE_UAV(MemberName)                                                                       \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::TextureUnorderedAccessView,                             \
        ::arda::render_graph::FARDGTextureUAVRef,                                                          \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::UnorderedAccess)

/** Declares an array of logical texture unordered-access view members. */
#define ARDG_TEXTURE_UAV_ARRAY(MemberName, Count)                                                          \
    ARDG_INTERNAL_PARAMETER_ARRAY(                                                                         \
        ::arda::render_graph::EARDGParameterType::TextureUnorderedAccessView,                             \
        ::arda::render_graph::FARDGTextureUAVRef,                                                          \
        MemberName,                                                                                        \
        Count,                                                                                             \
        nvrhi::ResourceStates::UnorderedAccess)

/** Declares a logical buffer shader-resource view member. */
#define ARDG_BUFFER_SRV(MemberName)                                                                        \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::BufferShaderResourceView,                               \
        ::arda::render_graph::FARDGBufferSRVRef,                                                           \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::ShaderResource)

/** Declares an array of logical buffer shader-resource view members. */
#define ARDG_BUFFER_SRV_ARRAY(MemberName, Count)                                                           \
    ARDG_INTERNAL_PARAMETER_ARRAY(                                                                         \
        ::arda::render_graph::EARDGParameterType::BufferShaderResourceView,                               \
        ::arda::render_graph::FARDGBufferSRVRef,                                                           \
        MemberName,                                                                                        \
        Count,                                                                                             \
        nvrhi::ResourceStates::ShaderResource)

/** Declares a logical buffer unordered-access view member. */
#define ARDG_BUFFER_UAV(MemberName)                                                                        \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::BufferUnorderedAccessView,                              \
        ::arda::render_graph::FARDGBufferUAVRef,                                                           \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::UnorderedAccess)

/** Declares an array of logical buffer unordered-access view members. */
#define ARDG_BUFFER_UAV_ARRAY(MemberName, Count)                                                           \
    ARDG_INTERNAL_PARAMETER_ARRAY(                                                                         \
        ::arda::render_graph::EARDGParameterType::BufferUnorderedAccessView,                              \
        ::arda::render_graph::FARDGBufferUAVRef,                                                           \
        MemberName,                                                                                        \
        Count,                                                                                             \
        nvrhi::ResourceStates::UnorderedAccess)

/** Declares a direct texture-access member whose state is set at runtime. */
#define ARDG_TEXTURE_ACCESS(MemberName)                                                                    \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::TextureAccess,                                          \
        ::arda::render_graph::FARDGTextureAccess,                                                          \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::Unknown)

/** Declares an array of direct texture-access members. */
#define ARDG_TEXTURE_ACCESS_ARRAY(MemberName, Count)                                                       \
    ARDG_INTERNAL_PARAMETER_ARRAY(                                                                         \
        ::arda::render_graph::EARDGParameterType::TextureAccess,                                          \
        ::arda::render_graph::FARDGTextureAccess,                                                          \
        MemberName,                                                                                        \
        Count,                                                                                             \
        nvrhi::ResourceStates::Unknown)

/** Declares a direct buffer-access member whose state is set at runtime. */
#define ARDG_BUFFER_ACCESS(MemberName)                                                                     \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::BufferAccess,                                           \
        ::arda::render_graph::FARDGBufferAccess,                                                           \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::Unknown)

/** Declares an array of direct buffer-access members. */
#define ARDG_BUFFER_ACCESS_ARRAY(MemberName, Count)                                                        \
    ARDG_INTERNAL_PARAMETER_ARRAY(                                                                         \
        ::arda::render_graph::EARDGParameterType::BufferAccess,                                           \
        ::arda::render_graph::FARDGBufferAccess,                                                           \
        MemberName,                                                                                        \
        Count,                                                                                             \
        nvrhi::ResourceStates::Unknown)

/** Declares a logical uniform-buffer member. */
#define ARDG_UNIFORM_BUFFER(MemberName)                                                                    \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::UniformBuffer,                                          \
        ::arda::render_graph::FARDGUniformBufferRef,                                                       \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::ConstantBuffer)

/** Declares an array of logical uniform-buffer members. */
#define ARDG_UNIFORM_BUFFER_ARRAY(MemberName, Count)                                                       \
    ARDG_INTERNAL_PARAMETER_ARRAY(                                                                         \
        ::arda::render_graph::EARDGParameterType::UniformBuffer,                                          \
        ::arda::render_graph::FARDGUniformBufferRef,                                                       \
        MemberName,                                                                                        \
        Count,                                                                                             \
        nvrhi::ResourceStates::ConstantBuffer)

/** Declares one recursively enumerated nested ARDG parameter struct. */
#define ARDG_PARAMETER_STRUCT(StructType, MemberName)                                                      \
    ARDG_INTERNAL_NESTED_PARAMETER(StructType, MemberName)

/** Declares an array of recursively enumerated nested ARDG parameter structs. */
#define ARDG_PARAMETER_STRUCT_ARRAY(StructType, MemberName, Count)                                         \
    ARDG_INTERNAL_NESTED_PARAMETER_ARRAY(StructType, MemberName, Count)

/** Declares raster render-target binding slots. */
#define ARDG_RENDER_TARGET_BINDING_SLOTS(MemberName)                                                       \
    ARDG_INTERNAL_PARAMETER(                                                                               \
        ::arda::render_graph::EARDGParameterType::RenderTargetBindingSlots,                               \
        ::arda::render_graph::FARDGRenderTargetBindingSlots,                                              \
        MemberName,                                                                                        \
        nvrhi::ResourceStates::RenderTarget)
