"""Build-time CUDA compiler discovery and deployment requirements."""


def cuda_build_sections(root, code, api_link):
    cmake = (root / "Docs/ArdaBackend/Examples/CMakeLists.txt").read_text(encoding="utf-8")
    return [
        ("nvcc-build", "Find nvcc on the build machine", '''
<p><strong>Deployment contract: end users do not need nvcc or a full CUDA Toolkit installed to run a packaged application.</strong> Locate the compiler when configuring the developer/CI build, compile the CUDA sources, and ship the resulting application/device artifacts plus its required runtime dependencies. Application startup should not search PATH for nvcc or compile missing kernels by invoking it.</p>
<p>The <a href="Examples/CMakeLists.txt">standalone example CMakeLists.txt</a> below builds <a href="Examples/ArdaCudaDirectLaunch.cu">the direct host helper</a>. It starts with CXX, probes CUDA only when the example is enabled, and fails during configuration if no usable compiler is available. Disabling the example skips CUDA discovery. The main Ardashir project remains CXX-only: ARDASHIR_ENABLE_CUDA and ARDASHIR_CUDA_INCLUDE_DIR enable provider/header support, not nvcc discovery. A directory containing cuda.h alone is insufficient to compile a CUDA host helper.</p>''' + code(cmake, 'cmake') + '''
<p>check_language(CUDA) records a compiler or NOTFOUND; a cached or explicit CMAKE_CUDA_COMPILER skips this probe, so enable_language(CUDA) still validates the selected toolchain. NVCC also needs a supported host C++ compiler. For Ninja on Windows, use an appropriate Visual Studio developer shell so cl.exe and the Windows SDK are available. See <a href="https://cmake.org/cmake/help/latest/module/CheckLanguage.html">CheckLanguage</a> and <a href="https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#supported-host-compilers">NVCC host compiler requirements</a>.</p>
<h3>Ninja or Makefile generators: pin the compiler before the first configure</h3>
<p>Use an absolute CMAKE_CUDA_COMPILER path for a reproducible build, or set CUDACXX before the first configure. CMake caches the selection; CUDACXX is ignored when CMAKE_CUDA_COMPILER is already defined. Use a new build directory when switching compilers/toolkits instead of expecting a changed PATH to replace the cached choice. See <a href="https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER.html">compiler selection</a> and <a href="https://cmake.org/cmake/help/latest/envvar/CUDACXX.html">CUDACXX</a>.</p>
<p>From the repository root, with Ninja installed and the host compiler environment ready (replace toolkit paths and architecture 80 for your build):</p>''' + code('cmake -S Docs/ArdaBackend/Examples -B build/cuda-helper -G Ninja "-DCMAKE_CUDA_COMPILER=C:/CUDA/bin/nvcc.exe" "-DCUDAToolkit_ROOT=C:/CUDA" -DCMAKE_CUDA_ARCHITECTURES=80 -DCMAKE_BUILD_TYPE=Release\ncmake --build build/cuda-helper --target ArdaCudaExample --verbose', 'shell') + '''
<p>Alternatively, on a POSIX shell, set the compiler for this configure process:</p>''' + code('CUDACXX=/usr/local/cuda/bin/nvcc cmake -S Docs/ArdaBackend/Examples -B build/cuda-helper-posix -G Ninja -DCUDAToolkit_ROOT=/usr/local/cuda -DCMAKE_CUDA_ARCHITECTURES=80 -DCMAKE_BUILD_TYPE=Release', 'shell') + '''
<h3>Visual Studio generators: select the CUDA toolset</h3>
<p>Visual Studio chooses its CUDA compiler through the generator toolset rather than a user-set CMAKE_CUDA_COMPILER. Specify an installed CUDA toolset version with -T cuda=&lt;version&gt;, or a standalone toolkit path with the required Visual Studio integration files. With no explicit selection, CMake chooses a default available toolset. A header-only SDK download does not supply that integration. See <a href="https://cmake.org/cmake/help/latest/variable/CMAKE_VS_PLATFORM_TOOLSET_CUDA.html">Visual Studio CUDA toolset selection</a>.</p>''' + code('cmake -S Docs/ArdaBackend/Examples -B build/cuda-helper-vs -G "Visual Studio 17 2022" -A x64 -T cuda=13.3 -DCMAKE_CUDA_ARCHITECTURES=80\ncmake --build build/cuda-helper-vs --config Release --target ArdaCudaExample --verbose', 'shell') + '''
<h3>Toolkit lookup is distinct from compiler selection</h3>
<p>After enabling CUDA, find_package(CUDAToolkit) searches first relative to that compiler. Its other documented hints include CMAKE_CUDA_COMPILER/CUDACXX, CUDAToolkit_ROOT, CUDA_PATH, PATH, the Unix /usr/local/cuda link and platform installation locations. Multiple default installations can be ambiguous. Pin the compiler and matching toolkit root on CI; CUDAToolkit_ROOT alone does not replace an already selected compiler or a Visual Studio toolset. Read the configure output and verbose compile commands to verify the result. See <a href="https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#search-behavior">the exact toolkit search order</a>.</p>
<p>The example creates a static helper library, not a complete application. Link it into the application that supplies the mappings, stream and completion adapter. A successful compile does not prove graphics interoperability or GPU execution.</p>'''),
        ("offline-ptx", "Generate PTX during the build for the existing RHI path", '''
<p>The descriptor method can also avoid runtime source compilation. On the build machine, compile each device-only source to PTX and package those files as application assets, or embed their bytes in the application. An illustrative build command for the first checked-in kernel is:</p>''' + code('nvcc --ptx --std=c++17 --gpu-architecture=compute_80 Source/ArdaBackend/Tests/ArdaCudaOperand.cu -o build/add_values.ptx', 'shell') + '''
<p>Use the compiler resolved by your build, generate the second stage from ArdaCudaOperandFinish.cu as well, and make the build depend on included .h/.cuh files so edits regenerate the artifacts. The command assumes the build directory exists.</p>''' + '<p>At runtime, load the packaged PTX into ' + api_link('FArdaCudaKernel::mPtx') + ', or a Ptx-language ' + api_link('FArdaCudaModule') + ' created without a compiler callback. Current RHI descriptors accept PTX text; they do not accept a .cubin or .fatbin substituted into mPtx. This is an application packaging recipe, not an existing automatic artifact-build target in Ardashir.</p>' + '''
<p>A driver may JIT PTX into native instructions when loading it. That is driver compilation, not a call to the nvcc executable. An incompatible PTX version, missing artifact or unsupported target should produce an actionable error or a previously selected supported graphics alternative, rather than asking the end user to install the compiler. See <a href="https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#supported-phases">NVCC output phases</a> and <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/03-advanced/driver-api.html">driver module loading</a>.</p>'''),
        ("runtime-deployment", "Ship runtime dependencies, not the compiler", '''
<p>Keep the build machine's toolkit paths out of the runtime configuration. Choose the deployment path explicitly:</p>
<ul><li><strong>Compiled CUDA host helper:</strong> ship the final linked application/library containing the host code and device images. The example selects CUDA_RUNTIME_LIBRARY Static and propagates CUDA::cudart_static to C++ consumers. Shared runtime linkage instead requires deploying the matching cudart shared library. Account separately for any other dynamically linked libraries; neither runtime choice removes the NVIDIA driver requirement. See <a href="https://cmake.org/cmake/help/latest/prop_tgt/CUDA_RUNTIME_LIBRARY.html">CUDA runtime linkage</a>.</li>
<li><strong>Prebuilt PTX through ArdaBackend:</strong> ship embedded/packaged PTX and the existing provider dependencies. This path loads neither nvcc nor NVRTC. The selected driver/native graphics extension must support the PTX and requested execution mode.</li>
<li><strong>Optional runtime NVRTC:</strong> only an application intentionally shipping runtime source compilation needs the NVRTC library, its matching builtins and its source/include inputs. NVRTC does not launch nvcc and does not require the user to install the full Toolkit. The runtime-source tests are optional; they are not the shipping contract for an ahead-of-time build.</li></ul>
<p>For compiled CUDA targets, set CMAKE_CUDA_ARCHITECTURES to the supported deployment GPUs. A value such as 80 generates both real and virtual code for that architecture; -real and -virtual suffixes select one form. Avoid native for distributable builds because it selects the build machine's GPUs. See <a href="https://cmake.org/cmake/help/latest/prop_tgt/CUDA_ARCHITECTURES.html">architecture selection</a>. Qualify the packaged device code and minimum driver together: an older driver may not understand PTX emitted by a newer toolkit. Static cudart does not solve that compatibility issue. See <a href="https://docs.nvidia.com/deploy/cuda-compatibility/minor-version-compatibility.html">NVIDIA's compatibility limits</a>.</p>
<p><strong>Release verification:</strong> run the packaged application on a machine/image with a supported driver and without nvcc, CUDA headers or a full Toolkit. Check first launch and subsequent launches, all packaged kernels, and graphics handoffs. Test with NVRTC absent for the precompiled paths; include only the runtime libraries your package deliberately uses. Verify that missing artifacts or unsupported drivers produce errors without attempting a compiler lookup. This is a release check to perform, not a new hardware qualification claim for the documentation helper.</p>'''),
    ]
