"""General CUDA/graphics chapter, rendered through the shared backend page shell."""


def cuda_graphics_chapter(api_link, page):
    sections = [
        ("fundamentals", "Where CUDA fits in a renderer", '''
<p>A renderer can combine rasterization, ray tracing and general GPU computation. For example, graphics can produce a noisy lighting image, a CUDA operation can process it, and a graphics pass can composite the result for presentation. CUDA supplies a GPU programming environment; the graphics API continues to own rendering and presentation in this arrangement.</p>
<p>A CUDA kernel is a GPU function marked __global__. A CPU host function selects a grid of thread blocks, provides arguments and queues the kernel. Threads derive an element index from blockIdx, blockDim and threadIdx. A bounds check handles a final partial block. The block is a cooperation unit; launch geometry is part of the algorithm. See <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/02-basics/intro-to-cuda-cpp.html">NVIDIA's CUDA C++ introduction</a>.</p>
<p>Consider CUDA when an operation already has a CUDA implementation or needs a native CUDA library. A graphics compute shader is also an option for buffer/image processing, particularly when the operation already fits existing shader bindings and graphics scheduling. Compare the complete integration cost and required device support. In Ardashir, an operand can explicitly choose a graphics implementation when its CUDA resources or execution mode are unavailable.</p>'''),
        ("launch", "Code preparation and scheduling are separate choices", '''
<p>There are two authoring methods in the <a href="cuda-interop.html#launch-methods">operand guide</a>. An application can compile a CUDA host helper and write Kernel&lt;&lt;&lt;Grid, Block, SharedBytes, Stream&gt;&gt;&gt;(Arguments). Alternatively, it can load device code, resolve an entry point and supply dimensions and argument storage to a Driver API launch. Both describe GPU work; their calling conventions and build artifacts differ.</p>
<p>ArdaBackend's implemented command-list interface uses PTX descriptors. <a class="term" data-term="ptx" href="../glossary.html#term-ptx">PTX</a> is a virtual GPU instruction representation that the driver prepares for a compatible device. The embedded test PTX and optional NVRTC-generated PTX feed the same path. <a class="term" data-term="nvrtc" href="../glossary.html#term-nvrtc">NVRTC</a> compiles device code; a .cu filename alone does not establish that a host launch function was compiled and linked. See <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/03-advanced/driver-api.html">module loading and driver launches</a> and <a href="https://docs.nvidia.com/cuda/nvrtc/index.html#language">NVRTC's compilation boundary</a>.</p>
<p>Scheduling is another choice: a host call can enqueue work into an ordinary CUDA stream, or an integration can record work for a graphics submission. Neither PTX nor triple-chevron syntax establishes a dependency on a graphics queue by itself. The <a href="cuda-interop.html#direct-launch">direct host helper</a> shows the syntax; the sections below explain what must surround it.</p>'''),
        ("memory", "Share storage and describe its interpretation", '''
<p>Sharing begins with a graphics allocation created for a supported export mechanism. Export an OS handle, import it into CUDA on the matching physical GPU, and create a CUDA mapping of the same storage. This can avoid a graphics-to-CPU-to-CUDA copy. A buffer mapping yields a device pointer; an image mapping yields a CUDA array/mipmapped array used through suitable access objects. Match the exported format, dimensions and allocation mapping. See <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/04-special-topics/graphics-interop.html#external-resource-interoperability">NVIDIA's external resource model</a>.</p>
<p>The memory handle and the synchronization handle have different jobs. Importing memory establishes access to storage. It does not establish when the graphics producer has finished writing. Likewise, sharing an allocation does not promise that every image format, mip, layer or usage is supported by a particular integration.</p>
<figure><div class="diagram-scroll" role="region" aria-label="Shared allocation and graphics CUDA handoff" tabindex="0"><img src="Assets/cuda-graphics-handoff.svg" alt="Graphics and CUDA views reference one allocation; graphics writes, CUDA updates, and graphics reads are ordered by two handoffs"></div><figcaption>One allocation has two API representations. The producer-to-consumer dependencies still require explicit ordering.</figcaption></figure>
<p>ArdaBackend makes sharing an allocation-time request through mbCudaInterop. Its buffer binding applies the view's byte offset before launching. Its surface binding selects a mip while keeping the image's array/depth addressing. A shader texture, a CUDA surface, and a contiguous tensor can represent related data with different layouts; packing, channel conversion and tensor strides remain explicit operation work. A raw Vulkan device address must not be used as a CUDA runtime pointer.</p>'''),
        ("ordering", "Establish both graphics-to-CUDA and CUDA-to-graphics order", '''
<p>A <a class="term" data-term="cuda-stream" href="../glossary.html#term-cuda-stream">CUDA stream</a> provides an ordered sequence of CUDA operations. Host launch return means submission, while completion is observed through synchronization or events. A graphics queue has its own timeline; CPU call order across two APIs is insufficient to join their GPU work. See <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/02-basics/asynchronous-execution.html">CUDA asynchronous execution</a>.</p>
<ol><li>Graphics writes the input and releases it for external access as required by the API.</li><li>Graphics signals a shared synchronization object after those writes.</li><li>CUDA waits on the imported object, runs the dependent kernels, then signals completion.</li><li>Graphics waits for CUDA and performs the required acquire/state transition before consuming the output.</li></ol>
<p>CUDA offers cudaImportExternalSemaphore, cudaWaitExternalSemaphoresAsync and cudaSignalExternalSemaphoresAsync for this handoff. Exportable fence/semaphore types and binary versus timeline semantics determine the exact parameters. Issue the matching signals and waits in a valid order; a wait on work that cannot yet run can deadlock. The diagram's labels A and B identify dependencies, not interchangeable values for every handle type. See the <a href="https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__EXTRES__INTEROP.html">external synchronization contract</a>.</p>
<p>This is a general integration pattern. ArdaBackend's current ordinary-context fallback instead uses CPU completion waits at graphics/CUDA boundaries. The public RHI does not expose an external-semaphore CUDA adapter. A CPU wait for CUDA is sufficient for the outgoing dependency only if the incoming graphics dependency and graphics resource transitions have also been established.</p>'''),
        ("modes", "Recognize the three execution paths in ArdaBackend", '<p>Read ' + api_link('FArdaCudaCapabilities') + ' after device initialization. The selected ' + api_link('EArdaCudaLaunchMode') + ' is the runtime result; the configured ' + api_link('EArdaCudaExecutionMode') + ' expresses a preference or requirement.</p>' + '''
<dl><dt>D3D12 CUDA in Graphics (CiG)</dt><dd>The provider matches adapter identity, creates a queue-associated CUDA context and uses cuStreamBeginCaptureToCig / cuStreamEndCaptureToCig to capture launches into the D3D12 graphics command list. The backend retains mappings, modules and stream state through graphics completion. This path requires its SDK/driver support and resource qualification. See the <a href="https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__STREAM.html">CiG stream capture API</a>.</dd>
<dt>Vulkan native CUDA launch</dt><dd>The provider records vkCmdCudaLaunchKernelNV in a graphics/compute command buffer. It uses the extension's module/function objects, resource representations, barriers and submission lifetime. This NVIDIA extension has its own support requirements; it is not ordinary CUDA-stream execution. See <a href="https://docs.vulkan.org/refpages/latest/refpages/source/VK_NV_cuda_kernel_launch.html">VK_NV_cuda_kernel_launch</a>.</dd>
<dt>Ordinary CUDA context (ContextSwitch)</dt><dd>Both providers can split a recorded list into graphics and CUDA segments. During submission the CPU waits for the preceding graphics segment, executes and synchronizes CUDA, then continues graphics. This conservative implementation serializes the dependent segments. Recording or discarding a list does not run its ordinary-context kernels.</dd></dl>
<p>Automatic prefers a qualified native path and falls back when native context or D3D12 surface qualification fails. GraphicsQueue requires native execution; ContextSwitch explicitly selects separate execution. Resource support remains per mode: the current Vulkan fallback excludes layered surfaces, while native Vulkan admits its qualified layered surfaces. Query surface flags and diagnostic reasons; do not infer them from buffer support. The <a href="cuda-interop.html#context-switch">submission timeline</a> and <a href="cuda-interop.html#qualification">qualification record</a> describe current repository behavior.</p>'''),
        ("worked-example", "Worked example: update data between two graphics passes", '''
<p>Use the repository's two-stage add operation to isolate handoff correctness before implementing image filtering. Let a graphics producer fill N = 130 unsigned 32-bit values with Input[i] = 3i. CUDA writes Output[i] = Input[i] + 7, then updates Output[i] += 11. The graphics consumer reads 3i + 18; readback should therefore contain 18 at index 0 and 405 at index 129.</p>
<ol><li>Allocate two shared buffers of at least 520 bytes and retain them. The sample operand requires each resolved input/output view to be exactly Count × 4 bytes: expose a 520-byte view for either larger allocation. For a guard-region test, place that working view inside a larger output allocation.</li><li>Record the graphics producer, then declare the operand's input Read and output ReadWrite. The second kernel reads the first kernel's output.</li><li>Choose 128 threads per block and two blocks. Of 256 launched threads, 130 access values and 126 return without accessing memory.</li><li>Use the <a href="cuda-interop.html#ptx-dispatch">implemented descriptor path</a>, or adapt the <a href="cuda-interop.html#direct-launch">direct host helper</a> with valid mappings and both handoffs. Both stages use the same data dependency.</li><li>Order the graphics consumer after CUDA, then wait for the final consumer/readback completion before comparing all 130 values and guard bytes.</li></ol>
<p>This 130-element exercise is a proposed application check, not a claimed additional executed GPU test. The linked backend tests provide the existing CPU-oracle, offset-view and multi-kernel examples. When extending the exercise to a texture, replace linear indexing with the selected mip's surface coordinates. When extending it to inference, explicitly pack the image into the library's required tensor layout before enqueueing inference.</p>'''),
        ("lifetime", "Retain resources until the last consumer finishes", '''
<p>For a frame slot, track the last operation that reads or writes each allocation. CUDA completion makes its output available to the next properly ordered consumer; it does not mean a later graphics consumer has finished. Reuse a slot only after that final consumer completes. Double or triple buffering needs a separate completion record for each slot.</p>
<p>For application-owned external-memory integration, complete outstanding GPU work before destroying its views, mappings or imported objects. Destroy CUDA surface/texture access objects before their backing arrays, free mapped pointers or mipmapped arrays, and then destroy imported memory. Keep synchronization objects alive until their pending waits/signals complete. The original graphics allocation must outlive all access. OS-handle ownership is handle-type-specific, so follow the import contract instead of always closing or always retaining every handle. See the <a href="https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__EXTRES__INTEROP.html">external resource lifetime rules</a>.</p>''' + '<p>For current RHI recording, retained ' + api_link('FArdaCudaBinding') + ' resources and provider batches carry submitted dependencies. In an application-owned direct ' + api_link('TArdaComputeOperand::Dispatch') + ', the implementation must provide that retention and completion contract. If the first launch succeeds and the second fails, already queued work still has dependencies; an error return does not cancel it.</p>'),
        ("performance", "Measure the complete graphics/CUDA boundary", '''
<p>Use an explicit cost model when choosing an implementation. For dependent work, an initial estimate is T = Tprepare + Tgraphics-in + Thandoff-in + Tpack + Tcuda + Tunpack + Thandoff-out + Tgraphics-out. Separate one-time compilation/import costs from steady-state per-frame costs. The expression is a planning model, not a measured claim about this GPU.</p>
<p>Compare the CUDA version with a graphics-shader version of the same operation and output. Include CPU submission stalls, image/tensor conversion, allocations and final frame latency. A faster CUDA kernel can still make the frame slower if its integration adds expensive handoffs or packing. ArdaBackend's ContextSwitch path specifically waits at every split, so combine compatible dependent kernels into one recorded CUDA sequence when that reduces boundaries.</p>
<p>Do not assume different APIs execute independently: independent streams may overlap when hardware and dependencies permit, while dependent work must wait. Use CUDA events for CUDA durations and graphics timestamps for graphics durations, then correlate them on a GPU timeline; unrelated timestamp domains cannot simply be subtracted. Warm caches before steady-state measurements and report first-use latency separately. See <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/02-basics/asynchronous-execution.html">streams, events and overlap</a>.</p>'''),
        ("failures", "Diagnose the boundary that failed", '''
<dl><dt>The .cu file exists, but dispatch still contains PTX</dt><dd>Check the build and loader. The repository's optional NVRTC path deliberately produces PTX for RHI descriptors. Use <a href="cuda-interop.html#launch-methods">the launch-method guide</a> to locate the actual host call.</dd>
<dt>Allocation works, but CUDA import or surface admission fails</dt><dd>Inspect device identity, sharing flags, format/dimensions and the selected mode's diagnostics. In ArdaBackend, query per-resource sharing and surface capabilities before selecting CUDA. Use the explicit graphics alternative when unavailable.</dd>
<dt>Output flickers, contains old values or corrupts another frame</dt><dd>Check both producer/consumer handoffs, view offsets and frame-slot reuse. Reduce to a known-value buffer test with guard bytes; verify every element after final completion. A successful memory import is not synchronization.</dd>
<dt>A launch reports success, but a later operation fails</dt><dd>Check asynchronous completion errors as well as immediate launch status. Preserve the first meaningful error, retain queued-work dependencies and avoid retrying a second implementation over partial writes.</dd>
<dt>Submission stalls or never completes</dt><dd>Separate expected ContextSwitch CPU waits from a synchronization cycle. Draw which operation signals every wait, verify timeline values or binary consumption, and ensure the producer can actually be submitted.</dd>
<dt>CUDA runs correctly but the frame gets slower</dt><dd>Measure handoffs and packing with the kernel. Compare steady-state frame time with the graphics implementation, and identify whether an ordinary-context split serialized unrelated work.</dd></dl>
<p>Use <a href="validation.html">native validation setup</a> and <a href="diagnostics.html">backend diagnostics</a> to preserve evidence. Distinguish a capability skip from an executed test. This guide changes documentation; it does not add a native-library runtime bridge, a direct CUDA RHI adapter, or new hardware qualification.</p>'''),
    ]
    return page(
        "How CUDA works with graphics",
        "Follow data from a graphics producer through CUDA computation to a graphics consumer, with explicit memory sharing, ordering and lifetime.",
        sections, "cuda-graphics-handoff.svg",
        checkpoints='''
<p>A correct graphics/CUDA operation needs compatible storage, a supported launch path and dependencies in both directions. Completion belongs to the final consumer of each allocation. These rules apply whether the host uses triple-chevron launches or PTX descriptors.</p>
<ol><li>Why is an imported memory handle insufficient to prevent stale output?</li><li>What changes between a linear buffer, a surface and an inference tensor?</li><li>Why does compiling a device .cu file with NVRTC not produce a host launch helper?</li><li>Which component owns completion in each of ArdaBackend's three execution paths?</li><li>For the 130-element example, how many threads return without accessing data and what is the final value at index 129?</li><li>Why can a frame slot remain busy after CUDA completes?</li></ol>
<p>Check answers in <a href="#ordering">ordering</a>, <a href="#memory">memory</a>, <a href="#launch">launching</a>, <a href="#modes">execution modes</a>, <a href="#worked-example">the worked example</a>, and <a href="#lifetime">lifetime</a>. Continue with the <a href="cuda-interop.html">two operand implementation methods</a>, <a href="resource-recipes.html">resource recipes</a>, and <a href="api-reference.html">canonical API reference</a>. NVIDIA and Khronos references are linked next to the mechanisms they specify; repository qualification is tracked in <a href="CUDA-Backend-Plan.md">the backend integration record</a>.</p>''',
        objectives='''
<p>Learn to explain what CUDA adds to a graphics pipeline, distinguish kernel launch syntax from GPU scheduling, trace a shared allocation across APIs, and determine when its memory may be reused. This is a general conceptual guide with a separate section mapping the model to current ArdaBackend behavior.</p>
<p>Prerequisites: basic C++, <a class="term" data-term="resource" href="../glossary.html#term-resource">GPU resources</a>, <a class="term" data-term="queue" href="../glossary.html#term-queue">queues</a>, and <a class="term" data-term="fence" href="../glossary.html#term-fence">completion fences</a>. Review <a href="commands.html">commands and synchronization</a> and <a href="rhi.html">resource ownership</a> as needed. For code, jump to <a href="cuda-interop.html#ptx-dispatch">RHI/PTX launches</a> or <a href="cuda-interop.html#direct-launch">ordinary CUDA C++ launches</a>.</p>''',
    ).replace("Executable examples and capability admission", "CUDA and graphics fundamentals")
