"""Source-backed single-kernel operand authoring and scheduling."""
import html
import re
from sync_api_inventories import evaluate_api
from cuda_build import cuda_build_sections


def cuda_chapter(root, api_link, page):
    tests = root / "Source/ArdaBackend/Tests"

    def code(value, language="cpp"):
        return f'<pre><code class="language-{language}">{html.escape(value)}</code></pre>'

    def example(name):
        return f'<details><summary>Read compiled example: {name}</summary>' + code((tests / name).read_text(encoding="utf-8")) + '</details>'

    sections = [
        ("model", "One operand selects and launches one compiled kernel", '''
<p>A <a class="term" data-term="compute-operand" href="../glossary.html#term-compute-operand">compute operand</a> is a schedulable unit: one parameter schema, a finite registry of precompiled entries, one selection decision and one kernel launch. A GEMM operand can register several tile sizes; selecting a tile does not schedule a second kernel. An algorithm requiring several kernels uses several operand dispatches or RDG passes, making intermediate resources and hazards visible.</p>
<p>The author implements BindKernelVariants and SelectKernel. The framework owns resource validation, parameter freezing, native mapping, dispatch and submission. This division lets the scheduler inspect logical resources before allocation while the backend resolves CUDA pointers only when physical resources exist. There is no user-overridable launch callback inside a registered variant.</p>'''),
        ("launch-methods", "Understand both CUDA launch spellings", '''
<p>Both methods below launch already compiled __global__ functions. In ordinary CUDA C++, Kernel&lt;&lt;&lt;Grid, Block, SharedBytes, Stream&gt;&gt;&gt;(P) gives nvcc the launch expression. A generic registry instead stores a compiled symbol and calls cudaLaunchKernel with the same dimensions, explicit stream and one argument block. The latter lets ordinary C++ scheduling code choose between typed kernel specializations without knowing CUDA syntax.</p>
<figure><div class="diagram-scroll" role="region" aria-label="Two native CUDA launch spellings" tabindex="0"><img src="Assets/cuda-launch-methods.svg" alt="nvcc builds one global kernel; direct chevron syntax or a registered entry invoke its native code on an explicit stream"></div><figcaption>Launch spelling does not choose the CUDA context, graphics queue or synchronization policy.</figcaption></figure>'''),
        ("ptx-dispatch", "Framework method: bind a native entry", '<p>' + api_link('TArdaCudaKernelVariant') + ' encodes the kernel symbol in its C++ type and pairs it with a host policy payload. ' + api_link('BindArdaCudaKernel') + ' builds the standard entry wrapper in an nvcc translation unit. The registry erases the distinct wrapper types only after runtime validation; it checks that every kernel takes the exact generated FCuda type by value, including type identity, size and alignment. Equal byte sizes alone do not make two schemas interchangeable.</p>' + example('ArdaCudaOperand.cu') + '''
<p>The bridge queries cudaFuncGetAttributes under the selected CUDA context, checks the entry's launch limits, patches resource fields in a private parameter copy, and calls cudaLaunchKernel. This is why the .cpp dispatcher has no triple-chevron expression. It no longer loads text, resolves string entry points or compiles device source. Diagnostic names identify variants; pointers identify executable entries.</p>'''),
        ("direct-launch", "Direct method: ordinary triple-chevron syntax", '''
<p>The standalone helper below demonstrates the language spelling using application-owned pointers and a CUDA stream. It computes +7 followed by +11. The caller must provide the correct current context, memory sharing, graphics handoffs and completion lifetime. It is a conceptual comparison, not an alternate override for the operand facade; the tested operand uses the registered method above.</p>''' + code((root / 'Docs/ArdaBackend/Examples/ArdaCudaDirectLaunch.cu').read_text(encoding='utf-8')) + '''
<p>The same two stages in Arda use two operand dispatches, with mBias equal to 7 then 11. Each operand launches once. cudaGetLastError reports immediate launch errors; completion can still report an asynchronous failure. Calling a direct helper while recording an RDG pass would bypass its submission contract. Do not obtain a Vulkan device address and treat it as an imported CUDA pointer. See <a href="https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__EXECUTION.html">CUDA runtime execution</a> and <a href="https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DRIVER.html">Runtime/Driver context interoperability</a>.</p>'''),
        *cuda_build_sections(root, code, api_link),
        ("operand", "Implement binding and selection", '<p>Derive ' + api_link('TArdaComputeOperand') + ' with a host parameter schema and a payload type. Retain the RHI device through its constructor. Implement GetName, BindKernelVariants and SelectKernel. Dispatch, DispatchDeferred, PrepareDispatch and GetOperandSupport are framework implementations; authors cannot override them.</p>' + example('ArdaTestComputeOperand.h') + '''
<p>Binding runs once per operand instance through synchronized initialization. It performs no CUDA initialization or launches. The first schema/registration error is retained even if the author ignores Add's returned status. Once frozen, the registry is immutable. Do not retain a mutable registry reference, recursively inspect support from BindKernelVariants, or mutate shared policy during concurrent dispatches. Exceptions from binding or selection become runtime error statuses.</p>
<p>SelectKernel receives only compatible candidates, capabilities, queue type and host parameters. It returns a candidate ID plus grid, block and dynamic shared-memory configuration, or an error. It must be a side-effect-free host decision: no allocation, CUDA calls, resource writes or asynchronous work. Device/kernel-specific thread and memory limits are validated again at native recording. An explicit NoWork choice is available for algorithms that permit empty work; zero grid dimensions do not imply NoWork.</p>''' + example('ArdaTestComputeOperand.cpp')),
        ("parameters", "One declaration produces host, CUDA and graph representations", '<p>' + api_link('ARDA_CUDA_PARAMETER_STRUCT') + ' expands a field-list macro into one parameter storage template. The public alias stores retained RHI resource views; its FCuda alias stores device pointers or 64-bit surface handles plus plain copied values. A Read buffer becomes const T* in CUDA, and writable buffers become T*. The device function takes that FCuda object as its only by-value argument.</p>' + example('ArdaCudaOperand.cuh') + '''
<p>Host references, device slots and graph handles have different layouts. Paired metadata records member offsets in each representation; the framework copies value fields individually into a zeroed argument block and patches resource slots after resolving mappings. It never memcpy-copies an entire host object containing reference-counted resources into CUDA.</p>
<p>Schema eligibility, unsupported value types, wrong kernel signatures, format/range/alignment errors, missing sharing and device affinity are runtime statuses. Ordinary C++/CUDA language rules still apply: syntax errors, invalid template expressions and illegal device code cannot be postponed to runtime. Plain value aggregates must not hide host pointers or undeclared resource dependencies. Raw scalar pointer fields are rejected; C++ reflection cannot discover pointers nested inside arbitrary user structs.</p>
<p>Automatic resource conversion means translating a declared buffer view into its mapped CUDA pointer and a declared texture storage format into a CUDA channel/array/surface representation. It does not normalize integers, change color space, repack tensors, swizzle channels or insert a conversion kernel. Surface fields declare an exact supported storage format and compatible element byte width. Unsupported normalized/sRGB/packed/compressed/depth/multisample/cube formats return an error. Use an explicit earlier pass for numerical or layout conversion.</p>
<p>Buffer ranges must be nonempty, in bounds, element-aligned and divisible by element size. A surface selects exactly one mip and all its array layers; the selected mode must support its dimensionality. Partial layer views are rejected. The sample additionally validates extent/count matching and disallows partially overlapping add views while allowing identical or disjoint ranges. Resource ownership is finally checked against the recording command list's device.</p>'''),
        ("dispatch", "Use one framework path for immediate and deferred work", '<p>' + api_link('TArdaComputeOperand::PrepareDispatch') + ' ensures bindings, validates resources, filters native coverage, calls selection and freezes one plan. Later edits to the caller\'s parameters do not change that plan. The plan retains device, resource views, values and entry ownership. ' + api_link('TArdaComputeOperand::DispatchDeferred') + ' records it into the supplied command list without submitting. ' + api_link('TArdaComputeOperand::Dispatch') + ' opens a list, records the same plan, submits and returns a device/queue/submission identity.</p>' + code('FArdaAddOperand Operand(Device);\nFArdaAddParameters P;\nP.mInput.mBuffer = Input;\nP.mOutput.mBuffer = Output;\nP.mCount = 128; P.mBias = 7;\n\n// Framework submits one kernel now. Success is not a CPU completion wait.\nauto Submitted = Operand.Dispatch(P);\nif (!Submitted) return Submitted.mStatus;\n\n// Or record one kernel into an already open, caller-owned list.\nauto Recorded = Operand.DispatchDeferred(Commands, P);\nif (!Recorded) return Recorded;\n// Caller closes/submits Commands and observes completion before host reuse.') + '''
<p>The example Input and Output are same-device buffers created with mbCudaInterop and valid producer dependencies. Reusing the same graphics queue preserves submission order; another queue requires an explicit QueueWait dependency or RDG scheduling. RecordPlan allows reuse of the frozen decision in a fresh recording; command lists containing CUDA remain single-use. NoWork returns submission identity zero and does not submit an empty kernel. Parameters still must satisfy preparation validation before NoWork selection.</p>'''),
        ("source-modules", "Organize translation units and retain native code", '''
<p>Keep the shared schema and operand declaration in a normal .h file. Put __global__ definitions in .cu or included .cuh files, and instantiate/bind them from nvcc-built .cu registration units. The .cpp BindKernelVariants implementation calls each exported registration function. This keeps CUDA syntax and headers out of ordinary application translation units and makes static-library extraction explicit.</p>
<p>Different profiles use different generated namespaces. Every registry entry retains its wrapper and immutable manifest; command recordings retain entries through completion, independently of the bounded per-context attribute cache. The checked-in helper links native code statically. Applications introducing unloadable modules must also keep their containing library loaded; an entry object alone cannot prevent an external DLL unload.</p>'''),
        ("tuning", "Enumerate finite template choices and choose using payloads", '<p>' + api_link('ForEachArdaCudaPermutation') + ' expands a C++17 integer sequence. Nested calls enumerate M/N/K tile dimensions; if constexpr can prune unsupported combinations before instantiation. Each instantiated symbol has its own wrapper type, while a shared payload type can hold M, N, K, alignment requirements or a human-readable tuning label. The payload guides selection and is not an extra kernel argument.</p>' + '''
<p>The sample binds block sizes 32 and 128, then chooses 32 for counts up to 64 and 128 otherwise. Grid.x = 1 + (Count - 1) / Block avoids overflow from Count + Block - 1. Manifest architecture coverage determines which native entries exist; algorithm requirements further filter them. A runtime-selected flag such as fast math must select a precompiled profile with that property. Do not silently label ordinary code as another architecture or infer coverage from a minimum capability alone.</p>
<p>Record variant ID, generated profile identity, device capability, input shape, block dimensions, shared bytes and measured time when tuning. Keep profiling outside SelectKernel and feed it an immutable chosen policy. Fast math changes numerical semantics, so an application must opt into that profile and validate its numerical tolerance.</p>'''),
        ("pixel-sort", "Run the resizable Pixel Sort example", '<p>' + api_link('PixelSort') + ''' is the backend-only Windows example in <code>Source/ArdaTests/Examples/PixelSort</code>. Its HLSL compute shader generates time-continuous domain-warped noise in an ink, indigo, lavender and coral palette. CUDA sorts the shared RGBA8UInt texture; a fullscreen graphics pass samples the result into the swap-chain back buffer. The target links ArdaBackend, its own native kernel library and Windows platform libraries, without RDG or scene dependencies.</p>
<p>Build it from the repository root after following the <a href="#nvcc-build">nvcc setup</a> section. For a clean Ninja build use a Visual Studio developer shell and choose native architectures matching the target GPU:</p>''' + code('cmake -S . -B build/pixel-sort -G Ninja -DCMAKE_BUILD_TYPE=Release -DARDASHIR_ENABLE_CUDA=ON -DARDASHIR_BUILD_CUDA_KERNELS=ON -DARDASHIR_BUILD_PIXEL_SORT=ON -DARDASHIR_BUILD_TESTS=OFF -DARDASHIR_CUDA_ARCHITECTURES="120"\ncmake --build build/pixel-sort --target PixelSort\nbuild/pixel-sort/Source/ArdaTests/Examples/PixelSort/PixelSort.exe --backend vulkan --cuda-mode auto', 'powershell') + '''
<p>Selection uses actual client dimensions. Width greater than or equal to height selects <code>RadixSort&lt;128, false&gt;</code>: 128 threads, four pixels per thread, 512-pixel row tiles and grid (ceil(width/512), height, 1). Portrait selects <code>RadixSort&lt;256, true&gt;</code>: 256 threads, 1024-pixel column tiles and grid (ceil(height/1024), width, 1). An integer-sequence binding loop instantiates both typed entries in one native build profile. Each entry takes the same generated FCuda object by value. Resize changes only the selected entry and dimensions; it never compiles CUDA.</p>
<p>This is segmented sorting. Within each tile, pixels whose integer luminance <code>(54*R + 183*G + 19*B) &gt;&gt; 8</code> is below the threshold delimit bright runs and remain fixed. A prefix count of those boundaries gives each pixel a run ID. Stable radix passes order the composite (run ID, selected channel) key; the complete RGBA pixel moves with its key, preserving the palette. Tile edges terminate runs, so the result is not a globally sorted row or column. Padding moves to the end and never writes outside the texture. The bounded tile keeps shared storage around 8/16 KiB plus counters and lets each block finish independently in one kernel launch. Column accesses are less contiguous; the two choices demonstrate a visual policy, not a proven optimum.</p>
<p>The renderer transitions noise to UAV, records compute, calls framework DispatchDeferred once, then transitions the shared textures to pixel-shader resource state before drawing. Binding a descriptor alone does not transition its texture. The Vulkan storage-image annotation is rgba8ui, matching RGBA8UInt; CUDA surface X coordinates are byte offsets (pixel X times four). The consumer divides integer colors by 255 explicitly. The backend supplies both graphics/CUDA handoffs described in <a href="cuda-graphics.html#ordering">the ordering model</a>. Normal frames use GPU ordering; resizing and shutdown wait before replacing or releasing resources. Minimizing suspends rendering, and restoring rebuilds the size-dependent resources.</p>
<p>Press C to cycle RGB keys (red by default), Space to pause, Tab to view the original, Up/Down to adjust the threshold, and Escape to close. The title shows the actual CUDA mode and selected direction/thread count. Enable tests with <code>cmake -S . -B build/pixel-sort -DARDASHIR_BUILD_TESTS=ON</code> and rebuild PixelSort. Then <code>ctest --test-dir build/pixel-sort -R "^PixelSort[.]" --output-on-failure</code> runs automatic, ordinary and forced graphics modes for both backends. Each test makes six actual Win32 resizes, checks every output pixel against a CPU stable-sort reference, and requires zero native validation errors. Partial/multiple tiles, both directions, all RGB keys and multiple thresholds are exercised. <code>--time 4 --frames 1 --capture portrait.png</code> freezes time and saves the rendered back buffer; see the ''' + api_link('PixelSort') + ''' contract for options and return codes.</p>
<p>Local Windows SM 120 qualification passes D3D12 automatic/ordinary execution and Vulkan automatic/ordinary/CUDA-in-graphics. D3D12 CiG surface qualification is unavailable on driver 610.62, so the forced graphics test skips with its reason. Workload or pixel mismatches remain failures. The runtime package contains the executable and deployed D3D12, Shaders and ShaderCompiler directories; this editable example caches HLSL graphics artifacts beside the executable using the included DXC. Its CUDA code is already linked, with no runtime nvcc, PTX or NVRTC path. Full source and the build/run README are in <code>Source/ArdaTests/Examples/PixelSort</code> in the repository.</p>'''),
        ("rdg", "Schedule logical resources before physical allocation", '''
<p>Use <a href="../ArdaRDG/api-reference.html#api-arda-tardgcudaparameters-86da79fe">TARDGCudaParameters</a> to rebind the same named fields to logical graph buffer/texture accesses. <a href="../ArdaRDG/api-reference.html#api-arda-addardacudapass-86c3c9ac">AddArdaCudaPass</a> derives read/write declarations at graph construction, retains a typed copy and the operand, and resolves physical RHI views during execution. The adapter then calls framework DispatchDeferred once. Read-only CUDA inputs preserve read hazards even when the native graphics resource state is UAV.</p>''' + code('FARDGBuilder Graph(MakeRenderGraphContext(Device));\nTARDGCudaParameters<FArdaAddParameters> P;\nP.mInput.mBuffer = Input;   // FARDGBufferRef, created with mbCudaInterop\nP.mOutput.mBuffer = Middle;\nP.mCount = 128; P.mBias = 7;\nauto First = AddArdaCudaPass(Graph, "add seven", Operand, P);\nif (!First) return First.mStatus;\nP.mInput.mBuffer = Middle; P.mOutput.mBuffer = Output; P.mBias = 11;\nauto Second = AddArdaCudaPass(Graph, "add eleven", Operand, P);\nif (!Second) return Second.mStatus;\n// Declare the output consumer/readback before Graph.Execute().') + '''
<p>Here Operand is a shared_ptr&lt;FArdaAddOperand&gt;, and Input/Middle/Output are graph buffers. A producer upload plus the two CUDA passes and a readback verifies Output[i] = Input[i] + 18 in ArdaCudaTests.cpp. Graph-created CUDA resources receive dedicated allocations, and pool matching includes the sharing flag. They cannot use transient placed-heap aliasing.</p>
<p>D3D12 CiG requires the graphics pipeline and ordered capture/submission. The adapter rejects AsyncCompute and adds NeverParallel plus RecordAtSubmit. Such passes record immediately before submission; a late failure can follow already submitted graph work, so inspect execution status and submitted instances. Outputs are not extracted on failure. Vulkan CiG and ordinary-context paths retain normal deferred graph recording. The scheduler owns cross-queue dependencies; the provider owns graphics/CUDA synchronization inside each list.</p>'''),
        ("fallback", "Choose an alternative before recording writes", '<p>' + api_link('TArdaComputeOperand::GetOperandSupport') + ' reports schema/registry/device/native-coverage admission without launching. Texture capability and actual allocation admission are separate. Automatic device mode prefers CiG and can use an ordinary context when CiG initialization or D3D12 surface qualification fails. GraphicsQueue pins CiG; ContextSwitch selects ordinary CUDA. These choices are fixed before resources are allocated.</p>' + '''
<p>The single-kernel operand does not automatically execute a graphics implementation or retry after a partial launch. Select an application graphics pass before recording CUDA when support or sharing is unavailable. Multi-kernel native libraries need a separately designed scheduling contract; they are not arbitrary callbacks hidden in this facade.</p>'''),
        ("qualification", "Verify outputs, packaging and capability failures", '''
<p>The native tests exercise D3D12 ContextSwitch, Vulkan ContextSwitch, D3D12 CiG and Vulkan CiG on Windows, RTX PRO 6000 Blackwell (SM 120), driver 610.62 with CUDA 13.3. Native buffers, frozen plans, immediate/deferred methods, offsets/guards and a two-pass RDG chain pass in all four modes. Nonzero-mip R32UInt surfaces pass in both ordinary contexts and Vulkan CiG. The D3D12 CiG surface probe fails with CUDA_ERROR_UNKNOWN, so that surface test explicitly skips and Automatic uses ordinary CUDA. Layered Vulkan imports remain disabled pending cross-API layout qualification.</p>
<p>Host tests reject incompatible schema/signature/layout/build metadata at runtime and exercise immutable registration, concurrent one-time binding and permutation filtering. The CUDA-disabled build still compiles the public facade and runs these tests. cuobjdump confirms the tested executable contains native sm_80/sm_120 code and no PTX. Other GPUs and operating systems are not covered by this local hardware qualification.</p>
<dl><dt>No compatible variant</dt><dd>Inspect generated target coverage, device capability and requirements; rebuild and redeploy the missing native profile. Do not invoke a runtime compiler.</dd><dt>InvalidArgument</dt><dd>Check exact FCuda signature, value eligibility, resource range/format/alignment and selected variant geometry. Preserve the first error.</dd><dt>WrongDevice</dt><dd>Use resources, operand and command list from the same RHI device; compare UUID/LUID when diagnosing native adapter selection.</dd><dt>Capture or replay failure</dt><dd>Submit or discard the previous D3D12 CiG list in capture order and create a fresh recording for repeated work.</dd><dt>Stale output or a hang</dt><dd>Draw both handoffs and final consumers. Inspect graphics validation, CUDA errors, semaphore signal/wait order and frame-slot lifetime. Never retry another implementation over partial writes.</dd></dl>
<p>Run the test executable with --gtest_filter=ArdaCompute*:ArdaCuda*:*ArdaCudaGpu*. See <a href="validation.html">validation setup</a> for required native layers and explicit skips, and <a href="CUDA-Backend-Plan.md">the implementation record</a> for qualification limits.</p>'''),
    ]
    rendered = page('Precompiled CUDA operands and graphics interoperability',
        'Declare one parameter schema, bind native kernel variants, select one launch, and let the framework submit it or schedule it through RDG.',
        sections, 'cuda-command-stream.svg', checkpoints='''
<p>A reusable operand separates finite build products, pure selection and framework execution. Check your understanding:</p><ol><li>Why do all registered kernels take FCuda rather than the retained host struct?</li><li>How does a template tile choice differ from a compiler flag profile?</li><li>Why does the generic dispatch use cudaLaunchKernel instead of visible triple-chevron syntax?</li><li>Which failures are runtime statuses, and which still belong to the C++ compiler?</li><li>When can the +7/+11 intermediate buffer be reused?</li><li>Why does D3D12 CiG require RecordAtSubmit in RDG?</li></ol>
<p>Find answers in <a href="#parameters">parameter representations</a>, <a href="#tuning">tuning</a>, <a href="#launch-methods">launch methods</a>, <a href="#rdg">RDG scheduling</a> and <a href="cuda-graphics.html#lifetime">completion lifetime</a>. Continue with <a href="cuda-graphics.html">CUDA in graphics fundamentals</a>, <a href="../ArdaRDG/index.html">RDG</a> and the <a href="api-reference.html">canonical API reference</a>. NVIDIA and CMake primary references are linked beside the mechanisms they specify.</p>''', objectives='''
<p>Learn to author an operand using BindKernelVariants and SelectKernel, build native variants with nvcc, and predict memory/queue ownership through immediate, deferred and graph execution. Prerequisites: <a href="cuda-graphics.html">CUDA in graphics</a>, <a href="commands.html">command submission</a> and <a href="rhi.html">resources</a>.</p>
<figure><div class="diagram-scroll" role="region" aria-label="CUDA operand representation and execution" tabindex="0"><img src="Assets/cuda-command-stream.svg" alt="One schema generates host values, CUDA argument slots and graph dependencies; selection freezes a single-kernel plan"></div><figcaption>Logical dependencies exist before physical pointers. The same frozen launch path serves both dispatch methods.</figcaption></figure>
<p>Expandable source examples are compiled backend tests. The standalone triple-chevron helper is explicitly separate. The old PTX/NVRTC route and user-overridden dispatch hooks have been removed.</p>''').replace('Executable examples and capability admission', 'CUDA authoring and execution')

    rdg_api = evaluate_api((root / "Docs/assets/arda-rdg-api.js").read_text(encoding="utf-8"), "ArdaRDGApi")
    for name in ("TARDGCudaParameters", "AddArdaCudaPass"):
        symbol = next(s for s in rdg_api["symbols"] if s["qualifiedName"] == "arda::" + name and s["kind"] in {"struct", "function"})
        rendered = re.sub(r"(?<=../ArdaRDG/api-reference.html#)api-arda-" + name.lower() + r"-[a-f0-9]+", symbol["id"], rendered)
    return rendered
