"""Build-time native CUDA variants and compiler-free deployment."""


def cuda_build_sections(root, code, api_link):
    return [
        ("nvcc-build", "Find nvcc when configuring the project", '''
<p><strong>nvcc belongs on developer and CI build machines. Packaged applications do not search for it or require a CUDA Toolkit installation.</strong> The root project starts with CXX. ARDASHIR_ENABLE_CUDA enables the provider bridge; ARDASHIR_BUILD_CUDA_KERNELS controls CUDA language discovery and defaults to the provider option. With kernel builds enabled, Cmake/ArdaCudaKernels.cmake clears a previous failed compiler lookup (NOTFOUND), calls enable_language(CUDA) directly, requires NVIDIA CUDA, and finds the matching CUDAToolkit. CUDA is required in this branch, so direct enablement preserves the actual compiler, host-toolchain or generator failure instead of replacing it with a generic missing-nvcc message. Provider includes default to the single toolkit directory containing cuda.h unless explicitly overridden; separate CCCL directories in CUDAToolkit_INCLUDE_DIRS are not treated as one path.</p>
<p>For Ninja on Windows, start in a Visual Studio developer shell with cl.exe and Windows SDK tools available. CMake can find nvcc on that shell's PATH, or through CUDACXX. To pin a specific toolkit on the first configure, supply an absolute compiler path and choose the native architectures you deploy:</p>''' + code('cmake -S . -B build/cuda -G Ninja -DARDASHIR_ENABLE_CUDA=ON -DARDASHIR_BUILD_CUDA_KERNELS=ON "-DCMAKE_CUDA_COMPILER=C:/CUDA/bin/nvcc.exe" "-DCUDAToolkit_ROOT=C:/CUDA" "-DARDASHIR_CUDA_ARCHITECTURES=89;120" -DCMAKE_BUILD_TYPE=Release\ncmake --build build/cuda --target ArdaBackendTests --verbose', 'shell') + '''
<p>CUDACXX is an alternative first-configure compiler hint for Ninja/Makefiles. CMake caches CMAKE_CUDA_COMPILER, so changing PATH or CUDACXX does not replace a successfully cached compiler. Arda retries an old NOTFOUND result on reconfiguration; an explicit invalid compiler path is reported as an error rather than silently replaced. Use a fresh build directory when changing toolchains. find_package(CUDAToolkit) prefers the enabled compiler's toolkit; CUDAToolkit_ROOT is a toolkit lookup hint, not an override of an already selected compiler. A folder containing only cuda.h cannot compile kernels. See <a href="https://cmake.org/cmake/help/latest/command/enable_language.html">enable_language</a>, <a href="https://cmake.org/cmake/help/latest/envvar/CUDACXX.html">CUDACXX</a> and <a href="https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#search-behavior">toolkit lookup order</a>.</p>
<p>If nvcc --version works but the Visual Studio generator reports no CUDA toolset, compiler availability alone is insufficient: that generator needs CUDA MSBuild integration. Use a fresh build directory with -G Ninja in a Visual Studio developer shell, or install/select the matching integration. The Pixel Sort launcher defaults to Ninja for new builds unless --generator or CMAKE_GENERATOR overrides it; existing generator caches are preserved. With a Visual Studio generator, select installed CUDA build integration using -T cuda=13.3 (or the installed version), together with -A x64. Do not substitute CMAKE_CUDA_COMPILER for the generator's toolset selection. See <a href="https://cmake.org/cmake/help/latest/variable/CMAKE_VS_PLATFORM_TOOLSET_CUDA.html">Visual Studio CUDA selection</a>. CiG needs CUDA 13.3+ provider headers and a supporting driver; ordinary external-memory execution needs CUDA 12+ headers. The selected nvcc must support every requested architecture. If compiler setup fails even with nvcc available, inspect the underlying CMake error (host compiler/Windows SDK, unsupported host version, incomplete toolkit, or target architecture); running nvcc --version does not compile or link a CUDA program. The configuring process must inherit the terminal's PATH; restart an IDE opened before toolkit installation or configure from the working terminal.</p>
<p>A build that only consumes already compiled operand libraries can set ARDASHIR_BUILD_CUDA_KERNELS=OFF. If it still compiles the CUDA provider, set ARDASHIR_CUDA_INCLUDE_DIR to matching SDK headers. A completely CUDA-disabled build sets both options OFF and requires neither compiler nor CUDA headers. The standalone <a href="Examples/CMakeLists.txt">direct launch example build</a> has its own ARDA_EXAMPLE_BUILD_CUDA option.</p>'''),
        ("offline-ptx", "Build native code separately for each flag and architecture profile", '''
<p>The former runtime compiler/module route has been removed. There is no PTX source, PTX asset loader, NVRTC adapter or runtime nvcc invocation in the operand facade or native providers. Missing native code returns Unsupported before recording a launch; deploy a rebuilt package for additional architectures.</p>
<p>Use ardashir_add_cuda_kernels once per independent profile. The helper creates a CUDA static library, compiles explicit native targets with the -real suffix, links static cudart, and generates ArdaCudaBuildInfo.h. Put kernel definitions and binding exports in ARDA_CUDA_BUILD_NAMESPACE so different flags cannot create duplicate symbols. These are the two compiled test profiles:</p>''' + code('ardashir_add_cuda_kernels(ArdaTestCudaPortable\n    PROFILE portable\n    SOURCES Tests/ArdaCudaOperand.cu\n    DEPENDS Tests/ArdaCudaOperand.cuh Tests/ArdaTestComputeOperand.h)\nardashir_add_cuda_kernels(ArdaTestCudaTuned\n    PROFILE tuned\n    SOURCES Tests/ArdaCudaOperand.cu\n    DEPENDS Tests/ArdaCudaOperand.cuh Tests/ArdaTestComputeOperand.h\n    ARCHITECTURES 120 FAST_MATH)', 'cmake') + '''
<p>ARCHITECTURES overrides the project list per target. FAST_MATH, DEFINITIONS and OPTIONS describe that profile's compilation; use CMake foreach to generate several targets for a finite application configuration set. Template tile choices inside one profile use C++ integer sequences. Build flags cannot be changed by a runtime loop: each flag combination must already be compiled and explicitly linked through its binding export.</p>
<p>DEPENDS lists included project headers that participate in the manifest identity; normal CUDA dependency scanning rebuilds changed includes as well. The generated identity hashes source contents, these explicit dependencies, profile, options, definitions, targets and compiler version. It is a diagnostic profile fingerprint, not a cryptographic identity for the complete transitive toolchain. Never key a persistent tuning cache only by a user-entered kernel name.</p>
<p>The helper rejects virtual targets and profile options that override code generation. It emits native images only; architecture suffixes a/f are treated conservatively as exact targets. Generic pre-Blackwell binaries may match a higher minor capability in the same major family; the current runtime requires exact capability for 100 and newer. Algorithm requirements can further restrict candidates but cannot add missing binary coverage. Check <a href="https://cmake.org/cmake/help/latest/prop_tgt/CUDA_ARCHITECTURES.html">CMake native architecture suffixes</a> and <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/01-introduction/cuda-platform.html">CUDA binary compatibility</a>. A new GPU may require a new package even if its compute capability is higher.</p>'''),
        ("runtime-deployment", "Package the executable and its runtime dependencies", '''
<p>Link the kernel libraries into the executable or an owned library and reference each binding export so static archive extraction keeps its kernels. The supplied helper selects static cudart. Ship the final native code and other required application libraries; a compatible NVIDIA driver remains required. If your own build chooses shared cudart or additional CUDA libraries, package those runtime dependencies explicitly. No nvcc executable, compiler headers, source text, or runtime compiler is part of this contract.</p>
<p>Qualification must include both packaging and GPU work: inspect each artifact with cuobjdump --list-elf and --list-ptx, run with the build toolkit absent from runtime PATH, and verify native launches, readbacks, unsupported architectures, first use and repeated use. Static cudart does not waive minimum driver requirements. See <a href="https://docs.nvidia.com/deploy/cuda-compatibility/minor-version-compatibility.html">driver compatibility</a> and <a href="https://cmake.org/cmake/help/latest/prop_tgt/CUDA_RUNTIME_LIBRARY.html">runtime linkage</a>.</p>
<p>The public .h facade is SDK-free. Only binding translation units include ArdaCudaKernelBinding.cuh and compile with nvcc; normal application .cpp files call the exported binding functions and framework dispatch. Compiled code must remain loaded through the last submission using it. The provided static-library workflow gives it process lifetime; hot-unloading plugin libraries is not an implemented facility.</p>'''),
    ]
