"""General CUDA/graphics memory and scheduling model, mapped to Arda's native paths."""


def cuda_graphics_chapter(api_link, page):
    sections = [
        ("fundamentals", "What CUDA adds to a graphics pipeline", '''
<p>CUDA executes NVIDIA GPU programs outside a graphics shading language. A renderer may use it for a tiled matrix operation, a simulation update or a custom filter between graphics passes. A graphics compute shader may solve the same problem with fewer API boundaries; CUDA becomes useful when its programming model or existing device code materially helps the workload.</p>
<p>Three independent questions determine correctness: which native code runs, how both APIs address the storage, and what orders producer/consumer accesses. A successful kernel compilation answers only the first question. Importing a shared allocation answers part of the second. Neither establishes a dependency between queues.</p>
<p>Think of one allocation with two legal views and two directional handoffs. Each view defines how bytes are interpreted; each handoff establishes when a consumer may access them. This model predicts why a pointer can be numerically nonzero yet invalid, or why a correct kernel can return stale output when graphics and CUDA overlap without a dependency.</p>'''),
        ("launch", "Kernel launch syntax does not choose the execution mode", '''
<p>A __global__ function is GPU code. A CPU launch uses grid dimensions (blocks), block dimensions (threads), dynamic shared-memory bytes and an explicit CUDA stream. Kernel&lt;&lt;&lt;Grid, Block, SharedBytes, Stream&gt;&gt;&gt;(P) is nvcc syntax. A registered native symbol can also be launched with cudaLaunchKernel and an argument-pointer array. Both forms invoke precompiled device code in this project.</p>
<p>The stream belongs to a CUDA context. The current context is host-thread state; pushing and restoring it selects the correct context for API calls. That host action is distinct from GPU scheduling between an ordinary CUDA context and a graphics context. Calling cudaSetDevice on an arbitrary worker is not an interop strategy: it can select a primary context unrelated to the provider's imported resources.</p>
<p>Arda hides native streams and pointer mappings inside its providers. The author binds __global__ symbols and selects launch dimensions; the framework launches them through its registered wrapper. See <a href="cuda-interop.html#launch-methods">both code spellings</a>, <a href="https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DRIVER.html">CUDA Runtime/Driver context rules</a> and <a href="https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__EXECUTION.html">kernel execution APIs</a>.</p>'''),
        ("deployment", "Compile at build time and deploy native images", '''
<p>nvcc compiles .cu translation units and their included .cuh device definitions during developer/CI builds. The application ships linked host entry wrappers and native GPU images. End users need the packaged runtime dependencies and a supported NVIDIA driver, not nvcc, headers or a full toolkit. A missing architecture is a package coverage error, not a request to compile on the user's machine.</p>
<p>Arda's helper builds one native architecture/flag profile per target, generates its coverage manifest and excludes PTX and runtime source compilation. Template instantiations enumerate finite tile choices inside a profile. Separate profiles isolate options such as fast math or different architecture sets. Follow <a href="cuda-interop.html#nvcc-build">project compiler discovery</a>, <a href="cuda-interop.html#offline-ptx">profile builds</a> and <a href="cuda-interop.html#runtime-deployment">runtime packaging</a>.</p>'''),
        ("memory", "Share storage and preserve its interpretation", '''
<p>Use the same physical adapter for graphics and CUDA: Windows D3D12 identifies it by LUID/node mask, while Vulkan uses its physical-device UUID. Allocate resources with external sharing enabled, export the platform handle and import it into the selected CUDA context. Importing another device's memory is not repaired by converting the handle's type.</p>
<p>A buffer is linear storage. Its CUDA view is the mapped base address plus the declared byte offset; the element type, alignment and range must agree with the kernel. A texture is usually tiled or otherwise opaque storage. Import it as a CUDA array with matching dimensions, channel format and mip structure, then create a surface object. A Vulkan buffer device address is not an ordinary CUDA pointer, and a graphics texture handle is not a surface object.</p>
<p>Arda's parameter schema automatically turns retained buffer views into pointers and supported raw texture formats into array/surface representations. It does not perform numerical conversion or tensor packing. For example, R32UInt becomes one unsigned 32-bit channel; a kernel expecting normalized float values needs an explicit conversion pass. An image tensor may also require a separate layout change from interleaved pixels to planar channels.</p>
<p>Declared Read/Write/ReadWrite access makes hazards visible. It does not sandbox a kernel: authors must honor the declared range and access. CUDA imports use dedicated graphics allocations; graph transient aliasing cannot silently reuse their backing memory. See <a href="cuda-interop.html#parameters">schema validation</a> and <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/04-special-topics/graphics-interop.html">NVIDIA graphics interoperability</a>.</p>'''),
        ("ordering", "Establish dependencies in both directions", '''
<figure><div class="diagram-scroll" role="region" aria-label="Graphics CUDA graphics producer consumer handoffs" tabindex="0"><img src="Assets/cuda-graphics-handoff.svg" alt="Graphics signals A after producing data; CUDA waits A, updates data and signals B; graphics waits B before consuming and retiring the frame slot"></div><figcaption>Memory sharing supplies legal views; handoffs supply ordering. Reuse follows the final consumer.</figcaption></figure>
<p>The graphics producer must make its writes visible before CUDA reads them. CUDA must finish its writes before the graphics consumer reads them. In a stream-based interop path, graphics signals a shared primitive, CUDA enqueues an external wait, the kernel runs, CUDA enqueues a signal, and graphics waits. These are GPU dependencies; the CPU can submit later work without waiting for each kernel to finish.</p>
<p>For D3D12 ordinary contexts, Arda creates a shared fence per segment: the graphics queue signals value 1, the CUDA stream waits for 1 and signals 2, and graphics waits for 2. For Vulkan, the segment has a pair of exported binary semaphores: graphics signals Ready, CUDA consumes Ready and signals Done, and graphics consumes Done. Binary primitives are single-consumption and belong to a single-use recording. Replaying the same list is rejected.</p>
<p>Vulkan resource ownership transfers remain necessary alongside semaphore synchronization. The provider releases shared buffers/images to the external queue family and reacquires them before the graphics consumer; shared images use GENERAL layout at the boundary. D3D12 inserts UAV ordering around CUDA segments. A semaphore does not excuse an invalid image layout or undeclared cross-queue resource use.</p>
<p>D3D12 CiG records CUDA into the D3D12 graphics list itself, using its ordered command stream plus barriers. This removes the separate segment handoff for captured work. Both designs still require lifetime through final graphics completion. See <a href="https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__STREAM.html">CiG stream capture</a>.</p>'''),
        ("modes", "Choose CiG or an ordinary CUDA context", '<p>The configuration ' + api_link('EArdaCudaExecutionMode') + ' expresses policy. The qualified result is ' + api_link('FArdaCudaCapabilities') + ', including launch mode, compute capability, surface flags and reasons for fallback. Capability admission is separate from allocation success.</p>' + '''
<p><strong>D3D12 CiG:</strong> create a CUDA context associated with the D3D12 graphics queue, begin capture to the actual native graphics command list, launch a registered compiled kernel on that stream, and end capture. The provider retains stream, entry and mappings through retirement. Its current capture gate permits one captured-but-unsubmitted list per context. RDG therefore records these passes at ordered submission, not in its earlier parallel recording waves.</p>
<p><strong>Vulkan CiG:</strong> reserve external compute queue capacity while creating the Vulkan device, create a VK_NV_external_compute_queue object with the preferred graphics queue, obtain its opaque external data, and create a CUDA CiG context from that NV blob. Kernels launch on a CUDA stream in this context. External memory imports, semaphore handoffs and queue-family transfers still apply. This implementation does not use the removed VK_NV_cuda_kernel_launch module/launch path. See <a href="https://docs.vulkan.org/refpages/latest/refpages/source/VK_NV_external_compute_queue.html">Vulkan external compute queues</a> and <a href="https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__CTX.html">CUDA CiG context creation</a>.</p>
<p><strong>Ordinary context (ContextSwitch):</strong> create a matched CUDA context independently of the graphics queue, import shared resources into it, and enqueue stream launches between GPU handoffs. The graphics and CUDA workloads belong to different GPU contexts; the driver schedules them according to its capabilities and policy. This is not a process-global cudaSetDevice toggle, nor does it require a CPU wait after every kernel. Arda pushes/restores its context on the calling thread and uses explicit streams.</p>
<p>Automatic prefers CiG, then ordinary CUDA if unavailable or if D3D12's surface probe fails. GraphicsQueue requires CiG; ContextSwitch forces ordinary execution. Pin the mode before creating resources. Borrowed Vulkan devices currently lack an external-queue reservation contract, so they cannot supply the Arda Vulkan CiG path; their enabled external-memory/semaphore extensions still determine ordinary-context support. Do not silently change a borrowed device's enabled extensions.</p>'''),
        ("worked-example", "Work through a graphics producer, two CUDA passes and a consumer", '''
<p>Suppose a graphics pass writes 130 uint32 values Input[i] = 3i. A CUDA stage adds 7 into Middle; another adds 11 into Output; graphics then consumes Output. Register a 128-thread kernel, with two blocks for each stage. The launch creates 256 threads; 126 threads must return without accessing the array because their index is at least 130.</p>
<p>In Arda, the two stages are separate single-kernel operands or two dispatches of the same operand with different biases. RDG sees Input as a read dependency, Middle as the first output and second input, and Output as the final output. It allocates dedicated shared buffers, resolves physical views during execution, and preserves the data dependency from the first CUDA pass to the second.</p>
<p>The expected final value is Output[129] = 3 × 129 + 7 + 11 = 405. Verify every element and guard bytes, not just that a launch returned success. The <a href="cuda-interop.html#rdg">compiled RDG recipe</a> uses 128 elements and tests the same +18 result in all four backend/mode combinations. Immediate Dispatch and caller-owned deferred recording share this launch implementation.</p>
<p>On ordinary-context and Vulkan CiG paths, each segment has a graphics-to-CUDA and CUDA-to-graphics GPU dependency. On D3D12 CiG, kernels are captured into ordered graphics lists. Separate passes expose intermediate lifetime and scheduling even when the implementation could algebraically combine the two additions; a production algorithm can choose to fuse them into one kernel explicitly.</p>'''),
        ("lifetime", "Retire resources after the last consumer", '''
<p>A successful enqueue means work was accepted, not that a resource is reusable. Retain the graphics allocation, imported CUDA memory, arrays/surfaces, stream, synchronization objects and compiled code while they can still be referenced. Arda recordings retain these dependencies; submitted recordings retire against the final graphics submission fence/timeline. The host parameter object may be destroyed after preparation because values and retained resource views have been copied.</p>
<p>A frame slot is reusable after its last consumer, which may be a graphics pass after CUDA. Waiting only for the kernel can overwrite data still being sampled or copied. Multiple in-flight frames need independent slots or an explicit last-use dependency. A captured list also needs its stream alive even though the CUDA calls that created the capture have returned.</p>
<p>On failure, preserve the first useful status. Arda drains partially enqueued CUDA work before releasing its resources, and rejects replay of failed/single-use batches. Normal successful handoffs remain asynchronous. Device WaitForIdle is an explicit completion operation for shutdown or host inspection; a Vulkan device-idle call alone does not cover an external compute queue unless completion has been joined back to graphics. Arda's final graphics wait performs that join.</p>'''),
        ("performance", "Measure the whole boundary", '''
<p>The relevant cost is graphics preparation + sharing/packing overhead + handoff latency + kernel time + consumer delay. A fast CUDA kernel can slow the frame if conversion or synchronization costs exceed its saving. Import mappings once per allocation; reuse operands and immutable registrations; avoid recreating resources each frame. Current synchronization primitives and stream batches belong to recordings, so very small kernels can still be dominated by setup and submission overhead.</p>
<p>CiG can reduce scheduling overhead, but it does not imply all resource types work or all work overlaps. Independent queues overlap only when dependencies and the GPU permit it. Benchmark steady-state frame time and latency for realistic shapes and frame counts, not just a warmed isolated kernel. Compare against a graphics compute implementation before choosing a production path.</p>
<p>Use GPU captures/timestamps to locate graphics stalls and NVIDIA profiling tools to inspect CUDA kernels. Include architecture/profile identity, selected tile and launch geometry in tuning records. The finite native registry gives repeatable candidates; benchmark-driven policy belongs outside the side-effect-free SelectKernel callback.</p>'''),
        ("failures", "Diagnose the failed boundary", '''
<dl><dt>Unsupported before launch</dt><dd>Check device match, driver/CiG support, native architecture coverage and resource sharing. Rebuild missing native profiles or select an application graphics path before writes.</dd><dt>Image mapping fails but buffers work</dt><dd>Inspect surface and layered-surface capability separately. On the tested Windows driver, D3D12 CiG image mapping fails; Automatic selects an ordinary context. Layered Vulkan imports remain excluded. Successful memory import alone is not proof of correct pixel addressing.</dd><dt>Old or flickering output</dt><dd>Check both handoffs, view offsets, queue-family ownership and reuse after the last consumer. Reduce to a known-value kernel with guards and final readback.</dd><dt>Submission never completes</dt><dd>Find the producer for every wait. Check binary semaphore consumption and fence values. A wait cannot complete if its signal is placed behind that same wait.</dd><dt>Launch succeeds but later completion fails</dt><dd>Preserve asynchronous errors, retain already queued work and discard the failed recording. Do not retry another algorithm over partial writes.</dd></dl>
<p>Use <a href="validation.html">graphics validation</a>, <a href="diagnostics.html">diagnostics</a> and <a href="CUDA-Backend-Plan.md">the hardware qualification record</a>. Distinguish a skipped capability from a passing GPU test. The single-kernel facade is not an adapter for arbitrary multi-kernel libraries or externally owned streams.</p>'''),
    ]
    return page('How CUDA works with graphics',
        'Trace shared storage, native kernel launches and GPU dependencies across D3D12, Vulkan and CUDA.',
        sections, 'cuda-graphics-handoff.svg', checkpoints='''
<p>Compatible storage, native code and ordered access are separate requirements. Check your model:</p><ol><li>Why does importing memory not make a graphics write visible to CUDA automatically?</li><li>Why is a Vulkan buffer device address different from a CUDA pointer?</li><li>How do D3D12 CiG, Vulkan CiG and ordinary contexts submit work?</li><li>Which GPU operation makes a frame slot reusable?</li><li>For 130 elements and blocks of 128, how many threads return early and what is Output[129]?</li><li>Why can a missing architecture require a package rebuild even on a newer GPU?</li></ol>
<p>Answers follow from <a href="#memory">memory interpretation</a>, <a href="#ordering">handoffs</a>, <a href="#modes">execution modes</a>, <a href="#worked-example">the worked example</a> and <a href="#lifetime">last-consumer lifetime</a>. Continue with <a href="cuda-interop.html">operand code and builds</a>, <a href="../ArdaRDG/index.html">RDG scheduling</a> and the <a href="api-reference.html">canonical API reference</a>. Primary NVIDIA/Khronos references appear beside the mechanisms they define.</p>''', objectives='''
<p>Learn to distinguish launch syntax from GPU scheduling, explain memory sharing, draw both handoffs and determine when data may be reused. This guide teaches the general model and maps it to current Arda behavior.</p>
<p>Prerequisites: C++, <a class="term" data-term="resource" href="../glossary.html#term-resource">GPU resources</a>, <a class="term" data-term="queue" href="../glossary.html#term-queue">queues</a> and <a class="term" data-term="fence" href="../glossary.html#term-fence">completion fences</a>. Review <a href="commands.html">commands and synchronization</a> as needed. For code, go to <a href="cuda-interop.html#launch-methods">both native launch methods</a>.</p>
<figure><div class="diagram-scroll" role="region" aria-label="Graphics CUDA dependency timeline" tabindex="0"><img src="Assets/cuda-graphics-handoff.svg" alt="Graphics and CUDA share storage with explicit dependencies in both directions"></div><figcaption>Share the allocation; order every producer and consumer; retire after the final use.</figcaption></figure>''').replace('Executable examples and capability admission', 'CUDA and graphics fundamentals')
