"""Teach tested RHI operands and a separately labeled direct CUDA host helper."""
import html
import textwrap


def cuda_chapter(root, api_link, page):
    tests = root / "Source/ArdaBackend/Tests"
    source = (tests / "ArdaCudaTests.cpp").read_text(encoding="utf-8")

    def region(first, last):
        return textwrap.dedent(source[source.index(first):source.index(last)]).strip()

    def code(value, language="cpp"):
        return f'<pre><code class="language-{language}">{html.escape(value)}</code></pre>'

    def example(name, language="cpp"):
        return f'<details><summary>Read compiled example: {name}</summary>' + code((tests / name).read_text(encoding="utf-8"), language) + '</details>'

    host_source = (tests / "ArdaTestComputeOperand.cpp").read_text(encoding="utf-8")
    recorded_launch = textwrap.dedent(host_source[
        host_source.index("        const uint32_t Block ="):
        host_source.index("        if (Status) { mLastBlockSize")]).strip()
    direct_source = (root / "Docs/ArdaBackend/Examples/ArdaCudaDirectLaunch.cu").read_text(encoding="utf-8")

    sections = [
        ("model", "Separate host execution, dependencies and device code", '''
<p>Learn to implement an operand that owns its CPU logic, launch policy and GPU work; describe resource dependencies in typed parameters; and choose immediate or deferred execution with explicit lifetime and ordering. Prerequisites: <a href="shaders.html">shader parameters and compilation</a>, <a href="rhi.html">RHI recording and submission</a>, and <a href="resource-recipes.html">resource allocation</a>.</p>
<p>A <a class="term" data-term="compute-operand" href="../glossary.html#term-compute-operand">compute operand</a> is a C++ object with a typed entry point. Its author may call several CUDA kernels, a native library, graphics compute, or a mixture. Source organization and tuning are ordinary implementation decisions. A parameter struct supplies host values and declares which resources are read or written. A command list, when used, describes work whose GPU execution happens after recording.</p>
<p>The CPU parameter object and the GPU kernel argument layout serve different purposes. Host shape vectors can guide tiling; resource declarations expose dependencies; dispatch then constructs the exact arguments required by each chosen kernel. No reflection layer can infer hidden pointer dependencies or a library's private tensor layout.</p>'''),
        ("launch-methods", "Two ways to launch the same CUDA computation", '''
<p>Start with <a href="cuda-graphics.html">How CUDA works with graphics</a> for the general memory and synchronization model. Here, both methods compute Output[i] = Input[i] + 18 with two ordered launches. The way kernel code is prepared and invoked is separate from whether an operand uses immediate execution or deferred recording.</p>
<ul><li><a href="#ptx-dispatch">Method 1: record PTX launch descriptors.</a> This is the implemented FArdaAddOperand sample. Plain C++ supplies PTX, entry-point names, dimensions and arguments to the RHI. Its .cu files are optional NVRTC inputs.</li><li><a href="#direct-launch">Method 2: compile a CUDA host helper with ordinary &lt;&lt;&lt;...&gt;&gt;&gt; calls.</a> The example below shows this authoring style. An application must provide its CUDA build/runtime and graphics interop adapter; the repository does not supply that adapter.</li></ul>
<figure><div class="diagram-scroll" role="region" aria-label="Two CUDA compilation and launch paths" tabindex="0"><img src="Assets/cuda-launch-methods.svg" alt="RHI descriptors accept PTX from NVRTC or an offline artifact; a CUDA-compiled host helper launches linked kernels through a stream"></div><figcaption>The presence of a .cu file does not tell you which path is used. Check who compiles it, what artifact is produced, and who launches it.</figcaption></figure>'''),
        ("ptx-dispatch", "Method 1: PTX descriptors and backend launches", '<p>The current sample creates ' + api_link('FArdaCudaKernel') + ' descriptors, places them in ' + api_link('FArdaCudaDispatch') + ', and calls ' + api_link('IArdaRHICommandList::DispatchCuda') + '. The excerpt below is read directly from <a href="https://github.com/DylanWaken/Ardashir/blob/master/Source/ArdaBackend/Tests/ArdaTestComputeOperand.cpp">ArdaTestComputeOperand.cpp</a>; the full helper and parameter validation appear under <a href="#source-modules">source modules</a>.</p>' + '''
<p><strong>Why PTX is still present:</strong> First.mPtx = AddPtx selects the embedded test kernel by default, allowing launch tests to run without the optional NVRTC compiler. Supplying two modules replaces that PTX with each module's GetPtx result. A precompiled PTX artifact can also feed the same descriptor. Moving kernel text to .cu files did not change this dispatch contract.</p>''' + code(recorded_launch) + '''
<p>mGridSize is the number of blocks; mBlockSize is threads per block; mSharedMemoryBytes is dynamic shared memory per block; mArguments follows the kernel parameter order. Binding(0/1) resolves retained resource views to provider-owned native values, while Value copies scalar bytes. These fields carry the information a &lt;&lt;&lt;Grid, Block, SharedBytes, Stream&gt;&gt;&gt; launch would otherwise supply, with the provider choosing the stream or graphics command buffer.</p>
<p>The <a href="https://github.com/DylanWaken/Ardashir/blob/master/Source/ArdaBackendImpls/Cuda/ArdaCudaInterop.cpp">CUDA driver bridge</a> loads PTX with cuModuleLoadDataEx, finds the entry with cuModuleGetFunction, and executes cuLaunchKernel. The <a href="https://github.com/DylanWaken/Ardashir/blob/master/Source/ArdaBackendImpls/Vulkan/ArdaVulkanBackend.cpp">native Vulkan path</a> records vkCmdCudaLaunchKernelNV. ContextSwitch records batches first and launches them during submission. This provider-level path preserves declared dependencies and resource lifetime.</p>
<p>NVRTC compiles device CUDA C++ into PTX in this adapter; it does not compile the host dispatcher containing ordinary kernel-launch syntax. An extern "C" __global__ definition supplies a stable entry name, not a linked host launch stub. See <a href="https://docs.nvidia.com/cuda/nvrtc/index.html#language">NVRTC language restrictions</a> and <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/03-advanced/driver-api.html">Driver API module loading and launches</a>.</p>'''),
        ("direct-launch", "Method 2: normal CUDA C++ host launches", '''
<p><strong>Documentation helper; no RHI adapter is implemented.</strong> The complete <a href="Examples/ArdaCudaDirectLaunch.cu">ArdaCudaDirectLaunch.cu</a> helper below runs the same +7 then +11 operation using a CUDA-compiled host function. It reuses one kernel for both stages. It is separate from the compiled backend tests and requires a CUDA-capable compiler such as nvcc plus the CUDA runtime.</p>''' + code(direct_source) + '''
<p>The launch syntax is Kernel&lt;&lt;&lt;Grid, Block, DynamicSharedBytes, Stream&gt;&gt;&gt;(Arguments). __global__ marks GPU code; LaunchArdaAddTwice executes on the CPU and queues it. Here each block has 128 threads and zero dynamic shared memory. Both launches use the same stream, so the second consumes the first's output. cudaGetLastError checks launch submission; a later completion check must also detect asynchronous execution errors. See <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/02-basics/intro-to-cuda-cpp.html">CUDA C++ kernel launch syntax</a> and <a href="https://docs.nvidia.com/cuda/cuda-programming-guide/02-basics/asynchronous-execution.html">stream ordering and completion</a>.</p>
<p>A simple application target containing this file can be built with the CMake fragment below. Select an architecture supported by your toolkit and target GPU. This is an application build recipe; Ardashir's current root project enables CXX only. ARDASHIR_ENABLE_CUDA enables its native providers and does not turn its test .cu files into nvcc-compiled host objects.</p>''' + code('cmake_minimum_required(VERSION 3.24)\nproject(ArdaCudaExample LANGUAGES CXX CUDA)\nfind_package(CUDAToolkit REQUIRED)\nadd_library(ArdaCudaExample STATIC ArdaCudaDirectLaunch.cu)\ntarget_link_libraries(ArdaCudaExample PUBLIC CUDA::cudart)\nset_target_properties(ArdaCudaExample PROPERTIES\n    CUDA_STANDARD 17 CUDA_STANDARD_REQUIRED ON)', 'cmake') + '<p>An implementation of ' + api_link('TArdaComputeOperand::Dispatch') + ' may call this helper after obtaining valid CUDA mappings, ordering the graphics producer and selecting the correct device/context. It must expose completion and retain resources until work finishes, including any successfully queued first stage when a later stage fails. For a simple blocking integration, check cudaStreamSynchronize(Stream) before returning control to graphics; an asynchronous integration needs a graphics-visible semaphore/fence handoff.</p>' + '''
<p>The public RHI exposes neither raw CUDA mappings nor native CUDA streams. GetCudaResourceInfo reports capabilities, not an address to pass into this helper. A Vulkan device address is not an ordinary CUDA pointer. Direct launches therefore require application-owned native storage/interop or a new explicit adapter. Calling this helper from DispatchDeferred without that adapter would execute outside RHI recording and ordering; retain the descriptor path for current command-list integration.</p>'''),
        ("operand", "Derive a typed operand and own its implementation", '<p>Derive ' + api_link('TArdaComputeOperand') + ' with your parameter type. Implement ' + api_link('FArdaComputeOperand::GetOperandSupport') + ' for the device/runtime you retain in your constructor, plus GetName for diagnostics. Override Dispatch for immediate execution and/or DispatchDeferred for command recording. The non-template ' + api_link('FArdaComputeOperand') + ' exposes identity, support and metadata; callers use the typed base to dispatch.</p>' + '''
<p>Dispatch is virtual C++ code: it can validate inputs, prepare scratch storage, invoke precompiled CUDA functions from any number of translation units, call runtime libraries, or record an RHI sequence. The base owns no device, compiler, kernel registry, variant selector or fallback policy. A support query returns a status with a reason and performs no launches. Each dispatch implementation must enforce support and validate the actual shape, dtype, layout, ranges, queue and resource compatibility it requires.</p>
<p>The compiled add example below binds its own RHI device and optional graphics implementation in the constructor. Its public parameters describe two buffer views, count and optional shapes. The separate host implementation below owns all selection and launch logic; the two CUDA files contain device logic.</p>''' + example('ArdaTestComputeOperand.h')),
        ("parameters", "Declare dependencies without defining a kernel ABI", '<p>Use ' + api_link('ARDA_BEGIN_COMPUTE_PARAMETER_STRUCT') + ' and its matching end macro as in the example. Value members contain ordinary host data; buffer and texture members retain RHI resources and ranges with author-declared Read, Write or ReadWrite access. Nested parameter structs and fixed arrays are recursively inspectable. Use a typedef for a comma-containing C++ type passed to a macro.</p><p>' + api_link('FArdaComputeParameterMetadata::Enumerate') + ' visits leaves in declaration order, with dotted paths and indices for arrays with multiple elements. ' + api_link('FArdaComputeParameterMetadata::GetResourceAccesses') + ' returns retained dependency declarations, preserving aliases, distinct byte/subresource ranges and null optional fields. Failure preserves the caller’s previous output. A Read input and a ReadWrite output may reference the same buffer; their declarations stay separate for a future graph adapter to resolve.</p>' + '''
<p>GetStaticMetadata describes standard-layout C++ objects, including normally copied nontrivial values such as the example's shape vectors. Copy the parameter object using its C++ copy semantics; never memcpy it as a serialized packet. Enumerate borrows leaf addresses, which become invalid when the instance dies. GetResourceAccesses retains resources independently of that instance, but does not retain arbitrary host pointers hidden in value fields.</p>
<p>This is the foundation for future RDG dependency tracking. No automatic RDG pass registration, graph-handle resolution, dependency merging, state transitions or kernel marshaling is implemented. Declare every external resource explicitly. Null may mean unused optional input; dispatch decides whether a field is required and validates its actual range, device and sharing. Metadata layout validation cannot prove that a user kernel respects the declared range.</p>''' + code('FArdaAddParameters Params;\n// Populate Params as in the complete dispatch example below.\neastl::vector<FArdaComputeResourceAccess> Dependencies;\nauto Status = Params.GetStaticMetadata().GetResourceAccesses(&Params, Dependencies);\n// A future graph adapter can import these declarations; this call schedules nothing.')),
        ("dispatch", "Choose immediate execution or deferred recording", '<p>' + api_link('TArdaComputeOperand::Dispatch') + ' runs the author’s CPU implementation now. It may directly launch CUDA or native library work in an author-owned context/stream. Success need not mean GPU completion: the implementation must document and expose its completion mechanism, retain in-flight resources and runtime objects, and coordinate external producers and consumers.</p><p>' + api_link('TArdaComputeOperand::DispatchDeferred') + ' also runs CPU logic now, but appends GPU work to a caller-owned open command list. The caller closes and submits it; the override must not close/submit it or launch external GPU work outside its ordering. Borrow parameters only during the call, and retain dependencies through eventual execution. An unimplemented hook returns Unsupported. In particular the default deferred hook never calls immediate Dispatch.</p>' + '''
<p>For the sample, immediate Dispatch deliberately creates, records and submits its own RHI list, returning a submission ID through its own mLastSubmission field. Deferred Dispatch uses the caller's list. That shared implementation is a choice made by this operand, not a restriction of the base. The buffer test records two ordered kernels, closes/submits, waits before mapping, and verifies offset views, guard bytes and every output element:</p>''' + '<details><summary>Complete recording, submission and readback test</summary>' + code(region('    TEST_P(ArdaCudaGpu, OrderedKernels', '    TEST_P(ArdaCudaGpu, SurfaceWrites')) + '</details><details><summary>Test fixture, allocation helper and source loader</summary>' + code(region('    class FCudaDiagnostics', '    TEST_P(ArdaCudaGpu, DefaultDeferredHook')) + '</details>'),
        ("source-modules", "Keep arbitrary CUDA source files behind Dispatch", '''
<p>The operand interface imposes no count or organization on .cpp, .cu or .cuh files. A build can compile/link CUDA translation units normally and expose host functions that Dispatch calls. No source-registration callback or framework kernel-selector function is needed. TensorRT engines or exported PyTorch kernel sequences can eventually use the same typed interface through implementation-owned runtime adapters; those integrations are not supplied here.</p>''' + '<p>For optional runtime compilation with <a class="term" data-term="nvrtc" href="../glossary.html#term-nvrtc">NVRTC</a>, ' + api_link('FArdaCudaModule') + ' owns one immutable source unit, named includes and compiler options, caching successful PTX per SM. Load as many units as your implementation needs, or supply precompiled PTX. This utility is independent of the operand base. Recreate a module when source, includes or compiler policy changes; failed compilations are not cached.</p>' + '''
<p>When source modules are supplied, the sample reads ArdaCudaOperand.cu plus ArdaCudaOperandFinish.cu as NVRTC input, with a .cuh → .h include chain. Without modules, it uses embedded PTX. Its host dispatch chooses block size and explicitly sequences the two exported kernels through descriptors, as shown in <a href="#ptx-dispatch">method 1</a>. This sample expects two modules because its operation has two stages; other operands may have any count. The NVRTC helper compiles each source separately; it does not device-link cross-unit symbols. Keep each unit self-contained, link ahead of time, or provide a custom compiler/linker adapter for cross-unit device calls. See <a href="#direct-launch">method 2</a> for a CUDA-compiled host function.</p>
<p>Link the optional Ardashir::ArdaCudaCompiler target and configure ARDASHIR_NVRTC_INCLUDE_DIR. CreateArdaNvrtcCompiler takes an absolute runtime library path; deploy NVRTC and its matching builtins on the launching process's library search path (PATH on Windows). The adapter targets compute_&lt;SM&gt;, preserves diagnostics and expects exported extern "C" kernels. No SDK types or mandatory NVRTC linkage enter the core interface. Precompiled/native library implementations need no NVRTC helper.</p>''' + example('ArdaTestComputeOperand.cpp') + example('ArdaCudaOperand.cu') + example('ArdaCudaOperandFinish.cu') + example('ArdaCudaOperandMath.cuh') + example('ArdaCudaOperandValue.h')),
        ("tuning", "Make shape and policy decisions inside dispatch", '''
<p>The sample's DispatchDeferred checks architecture, queue and sharing, then selects a graphics path or its CUDA sequence using ordinary if statements. It chooses a 32-thread block for shapes whose last axis is at most 64, otherwise 128. Two inputs can have the same element count while preferring different tiling. Shapes are host values: they do not imply tensor layout, strides, allocation size or dtype.</p>
<p>For an operation with tuned algorithms, keep caches and profiling policy in its implementation. Key reusable choices by relevant shape, dtype, layout, architecture and runtime state. Benchmark with scratch resources or otherwise preserve operation semantics; trying candidates on live output can duplicate writes. Synchronize mutable caches and scratch storage if dispatch is concurrent. The sample's mutable diagnostic fields require caller serialization.</p>
<p>The test holds count at 128, changes shapes from [4, 32] to [1, 128], observes block size 32 then 128, and checks input + 18 each time. The two source modules compile only once each. It then calls the typed virtual immediate hook on the output in place, waits for its submission, and checks input + 36:</p>''' + '<details><summary>Multi-file compilation, shape policy and immediate dispatch test</summary>' + code(region('    TEST_P(ArdaCudaGpu, TypedDispatch', '    TEST_P(ArdaCudaGpu, UserDispatch')) + '</details>'),
        ("fallback", "Choose alternatives before recording writes", '''
<p>A graphics alternative is optional user implementation code. The sample accepts an HLSL dispatch callback, checks input/resource compatibility and invokes it when sharing is unavailable or its own mbPreferGraphics setting is true. The base neither registers nor selects alternatives. GetOperandSupport can report support through a supplied graphics path even with CUDA disabled, but shape and resource checks still belong to dispatch.</p>
<p>Make fallback decisions before recording dependent writes. Once compilation or recording of the chosen path fails, propagate the error; retrying another path in a partially recorded list can duplicate work. The sample checks all inputs and compiles both source modules before submitting its sequence to DispatchCuda. The RHI still checks kernel launch descriptors and native constraints.</p>
<p>The complete graphics → operand → graphics test verifies input + 54, while nonshared resources exercise the graphics alternative. The callback owns shader transitions, bindings and compute pipeline setup:</p>''' + '<details><summary>Mixed graphics/CUDA and graphics alternative test</summary>' + code(region('    TEST_P(ArdaCudaGpu, GraphicsFallback', '    TEST_P(ArdaCudaGpu, RejectsInvalid')) + '</details>' + example('ArdaCudaFallback.hlsl', 'hlsl')),
        ("build", "Enable backend CUDA independently of the interface", '''
<p>The typed base, metadata and host-only dispatch work without CUDA. Enable backend CUDA sharing/DispatchCuda using the options below. Ordinary-context execution accepts CUDA 12.0+ headers; D3D12 CiG capture requires CUDA 13.3+. Native Vulkan launch uses Vulkan extension declarations. Runtime support is probed independently of the headers installed.</p>''' + code('cmake -S . -B build/cuda-on -DARDASHIR_ENABLE_CUDA=ON -DARDASHIR_CUDA_INCLUDE_DIR="C:/CUDA/include"\ncmake --build build/cuda-on --config Debug --target ArdaBackendTests ArdaBackendPublicHeaders\ncmake -S . -B build/cuda-off -DARDASHIR_ENABLE_CUDA=OFF', 'shell') + '<p>Use your local SDK/build paths. Public headers contain no CUDA SDK types. Native library dependencies for a custom Dispatch belong to that implementation’s build target. A successful build does not establish runtime architecture, library or sharing support.</p>'),
        ("resources", "Allocate shared storage and inspect actual representations", '<p>Query ' + api_link('FArdaCudaCapabilities') + ' on the device, then ' + api_link('FArdaCudaResourceInfo') + ' on each allocation. An adapter supporting CUDA does not make every graphics allocation shareable. Set mbCudaInterop at creation; an existing ordinary buffer cannot be converted by toggling metadata.</p>' + code('FArdaRHIBufferDesc Desc;\nDesc.mByteSize = 1024;\nDesc.mUsage = EArdaRHIBufferUsage::ShaderResource | EArdaRHIBufferUsage::UnorderedAccess;\nDesc.mbCudaInterop = true;\nauto Shared = Device->CreateBuffer(Desc);\nif (!Shared) { /* inspect the status and choose an explicit allocation/implementation */ }') + '''
<p>Current providers admit dedicated nonempty device-local buffers. CPU-visible, sparse/tiled, virtual/placed, versioned and acceleration-structure storage buffers are rejected. Views retain the underlying resource. Vertex/index/instance source buffers can be shared when their allocations qualify; an opaque graphics acceleration structure is not a CUDA/OptiX traversal handle.</p>
<p>Qualified texture storage uses 24 raw R/RG/RGBA integer formats (8/16/32-bit channels) or floating formats (16/32-bit channels). Dimensions are 1D, 1D array, 2D, 2D array and 3D, subject to execution-mode qualification below. Normalized, sRGB, BGRA, packed, compressed, depth, cube and multisample images are rejected. Native imports cannot opt into sharing without provider-owned export/mapping lifetime.</p>
<p>The public RHI does not expose these resources as raw CUDA pointers or native streams. A direct library-backed Dispatch must own suitable native allocations/interop and synchronization, or gain an explicit adapter. The typed interface permits such code; it does not implement TensorRT/PyTorch memory conversion or a deferred native-library bridge.</p>'''),
        ("packing", "Make image-to-tensor layout conversion explicit", '''
<p>Buffer bindings provide a private linear device address with view offset applied. Texture bindings provide a surface handle for one selected mip and its layers/depth. Surface access does not sample/filter, normalize, swizzle, convert sRGB or transpose tensor data. Follow the surface instruction's byte-based x addressing and the selected mip's dimensions.</p>
<p>A library expecting contiguous NCHW/NHWC data cannot consume tiled image storage as a flat pointer. Implement surface-to-buffer packing before the tensor operation, declare the source image Read and destination buffer Write, and order the consumer after it. Include shape, strides and dtype in host parameters and validate them in Dispatch. This makes dependencies visible and leaves layout conversion under the operator author's control.</p>''' + '<details><summary>Selected-mip surface kernel and graphics readback</summary>' + code(region('    TEST_P(ArdaCudaGpu, SurfaceWrites', '    TEST_P(ArdaCudaGpu, TextureFormat')) + '</details>'),
        ("context-switch", "Understand when recorded GPU work executes", '''
<p>Set FArdaBackendConfiguration::mCudaExecutionMode before initialization. Automatic prefers native graphics-queue execution, then uses an ordinary CUDA context when native execution is unavailable or D3D12 image qualification fails. GraphicsQueue pins native execution; ContextSwitch forces separate execution on both APIs.</p>
<p>In ContextSwitch mode, DispatchCuda records owned CUDA segments without launching. Submission completes preceding graphics work, executes an ordinary CUDA stream to completion, then resumes graphics. It blocks the submitting CPU at each boundary, preventing graphics/CUDA overlap; the final graphics segment retains ordinary fence completion. Arguments, modules and resources survive until completion. Reset discards unsubmitted work and replaying a CUDA recording is rejected.</p>
<figure><div class="diagram-scroll" role="region" aria-label="Context-switching execution timeline" tabindex="0"><img src="Assets/cuda-context-switch.svg" alt="Graphics segments and ordinary CUDA batches alternate with completion waits at submission boundaries"></div><figcaption>CPU recording precedes execution. Submission performs the waits and CUDA work; the timeline scrolls within this region on narrow screens.</figcaption></figure>
<p>Vulkan fallback requires an enabled OS external-memory extension, dedicated exported memory, matching CUDA UUID and ownership release/acquire barriers. Serialize access to borrowed queues. Vulkan ContextSwitch currently rejects layered surfaces after their cross-API readback failed qualification; mbLayeredSurfaceAccess reports this. D3D12 ordinary-context mode supports all five qualified dimensions. Native Vulkan retains array support. Use a graphics allocation and explicit alternative when sharing is unavailable.</p>'''),
        ("native", "Respect native queue ordering and object lifetime", '''
<p>D3D12 CiG matches the adapter LUID and CUDA device, creates a queue-bound context, imports shared committed memory and captures kernels into the graphics list. UAV barriers order accesses. Submit or discard a captured list before another capture on that context; captured lists are single-use. Streams, mappings and executable modules remain retained through graphics-fence retirement.</p>
<p>Vulkan VK_NV_cuda_kernel_launch records directly in a graphics/compute command buffer. Buffer device addresses are valid for this path, not arbitrary CUDA runtime calls; VK_NVX_image_view_handle supplies surface handles. Memory barriers and submission retention order consumers and preserve resources/modules. Copy queues are unsupported. Sharing availability is not permission for simultaneous writes.</p>
<p>The CUDA driver bridge checks kernel parameter metadata where the driver exposes it. Native Vulkan has no equivalent query here; custom PTX authors must match parameter counts, sizes and layouts. Both providers validate declared ranges and launch limits, which cannot establish arbitrary kernel memory safety.</p>'''),
        ("qualification", "Diagnose failures and reproduce the evidence", '''
<p>The compiled examples run on native D3D12/Vulkan, forced context-switching paths and pinned D3D12 CiG where available. The test machine is Windows with RTX PRO 6000 Blackwell (SM 120), driver 610.62 / CUDA 13.3. D3D12 CiG surface mapping fails on this driver; automatic mode uses an ordinary context. Native Vulkan and ordinary D3D12 surface tests qualify all 24 formats × 5 dimensions, while Vulkan ContextSwitch excludes layered images. Other GPUs, older installed drivers, native-library adapters and other operating systems remain unqualified.</p>
<dl><dt>Unsupported operand</dt><dd>Inspect the user implementation's support status, device/runtime and chosen path. For shared RHI work, check SM, queue and each resource's representation. Select an alternative before writes.</dd><dt>InvalidArgument</dt><dd>Check required typed parameters, shape/count consistency, range bounds, alignment, dtype/layout and kernel ABI. Metadata is not a substitute for these checks.</dd><dt>Compiler failure</dt><dd>Inspect preserved diagnostics, include names and runtime/builtins deployment. Rebuild source modules after changes. Do not retry a graphics path after partial recording.</dd><dt>Capture or replay failure</dt><dd>Discard/reset the failed recording and obey CiG submit/discard ordering. Re-record intentional repeated work.</dd><dt>Skipped GPU test</dt><dd>Distinguish missing validation, unavailable CUDA and missing optional NVRTC library. A skip is not evidence of GPU execution; see <a href="validation.html">validation setup</a>.</dd></dl>
<p>Run ArdaBackendTests in CUDA-on and CUDA-off builds. For focused checks use the filter below, with ARDA_TEST_NVRTC_LIBRARY set to the absolute NVRTC library path and the builtins directory on PATH when the NVRTC adapter is configured. Leave that variable unset in a build without NVRTC headers; explicitly requesting compilation from an unavailable adapter is a test failure. CPU-only metadata/host dispatch tests run without that library. The GPU tests verify output values, guards, multi-file compilation caching, deferred execution, support rejection and graphics alternatives.</p>''' + code('ArdaBackendTests --gtest_filter=ArdaCompute*:ArdaCudaModule.*:ArdaCudaCompiler.*:*ArdaCudaGpu*', 'shell')),
    ]
    rendered = page('Typed compute operands and CUDA interoperability',
                'Implement your own typed Dispatch, describe resource dependencies, and compose CUDA sources or runtime calls with explicit execution and lifetime.',
                sections, 'cuda-command-stream.svg', '''
<p>An operand author owns execution, validation and policy. Typed metadata exposes resource dependencies without dictating a kernel ABI. Deferred recording requires an ordered submission path; immediate launches require an implementation-defined completion contract.</p>
<ol><li>Why does the current .cu-based sample still pass PTX to DispatchCuda?</li><li>Which build, memory and synchronization responsibilities must a direct &lt;&lt;&lt;...&gt;&gt;&gt; implementation supply?</li><li>Where would an immediate TensorRT enqueue and its stream ownership live?</li><li>Why can a default deferred hook not safely call an immediate hook?</li><li>How do aliasing views, null optional resources and shape vectors appear in metadata?</li><li>Why do [4, 32] and [1, 128] select different blocks while producing the same values?</li><li>What changes when a surface is unqualified or a selected compilation fails?</li></ol>
<p>Use <a href="#launch-methods">the two launch methods</a>, <a href="#dispatch">dispatch</a>, <a href="#parameters">parameters</a>, <a href="#tuning">policy</a> and <a href="#fallback">alternatives</a> to check your answers. Continue with <a href="cuda-graphics.html">CUDA in graphics fundamentals</a>, <a href="../ArdaRDG/index.html">RDG fundamentals</a>, <a href="shaders.html">shader authoring</a>, <a href="diagnostics.html">diagnostics</a>, and the <a href="api-reference.html">canonical API reference</a>.</p>''', objectives='''
<p>Learn to distinguish PTX descriptor launches from CUDA-compiled host launches, implement a typed operand, and assign resource lifetime and synchronization to the component that actually submits work. Prerequisites: <a href="cuda-graphics.html">CUDA in graphics fundamentals</a>, <a href="commands.html">command recording</a>, and <a href="rhi.html">resources and ownership</a>.</p>
<p><strong>Example status:</strong> the RHI descriptor excerpts and expandable tests come from compiled backend sources. The direct CUDA host helper in method 2 is a documentation example with application-owned pointer/stream prerequisites; it is not an implemented or GPU-qualified ArdaBackend adapter. Optional test .cu sources are compiled by NVRTC only when the runtime-source tests are enabled.</p>
<figure><div class="diagram-scroll" role="region" aria-label="Typed operand execution model" tabindex="0"><img src="Assets/cuda-command-stream.svg" alt="Typed parameters feed immediate or deferred dispatch; metadata inspection schedules nothing"></div><figcaption>Dispatch defines execution and completion; parameter metadata describes dependencies.</figcaption></figure>''')

    return rendered.replace("Executable examples and capability admission", "CUDA authoring and execution")
