include_guard(GLOBAL)

# Compiler discovery occurs only during project configuration. Applications never search for nvcc.
macro(ardashir_enable_cuda_compiler)
    include(CheckLanguage)
    check_language(CUDA)
    if(NOT CMAKE_CUDA_COMPILER)
        message(FATAL_ERROR "CUDA kernel builds require nvcc at build time. Set CMAKE_CUDA_COMPILER or CUDACXX (Ninja), or select the CUDA Visual Studio toolset. Disable ARDASHIR_BUILD_CUDA_KERNELS for a consumer-only build. Deployed applications do not require nvcc.")
    endif()
    enable_language(CUDA)
    if(NOT CMAKE_CUDA_COMPILER_ID STREQUAL "NVIDIA")
        message(FATAL_ERROR "Arda precompiled CUDA variants require the NVIDIA CUDA compiler.")
    endif()
    find_package(CUDAToolkit REQUIRED)
    if(NOT ARDASHIR_CUDA_INCLUDE_DIR)
        set(ARDASHIR_CUDA_INCLUDE_DIR "${CUDAToolkit_INCLUDE_DIRS}")
    endif()
endmacro()

# One target per architecture/flag profile. Refer to exported bindings explicitly so static
# archive extraction retains every registered entry. Put kernels in ARDA_CUDA_BUILD_NAMESPACE.
function(ardashir_add_cuda_kernels Target)
    cmake_parse_arguments(K "FAST_MATH" "PROFILE" "SOURCES;DEPENDS;ARCHITECTURES;DEFINITIONS;OPTIONS" ${ARGN})
    if(K_UNPARSED_ARGUMENTS OR NOT K_SOURCES)
        message(FATAL_ERROR "ardashir_add_cuda_kernels requires SOURCES and recognized named arguments.")
    endif()
    if(NOT CMAKE_CUDA_COMPILER_LOADED)
        message(FATAL_ERROR "Enable ARDASHIR_BUILD_CUDA_KERNELS before adding CUDA kernel targets.")
    endif()
    if(NOT K_PROFILE)
        set(K_PROFILE "${Target}")
    endif()
    if(NOT K_PROFILE MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        message(FATAL_ERROR "CUDA PROFILE must be a C++ namespace identifier.")
    endif()
    get_property(Profiles GLOBAL PROPERTY ARDA_CUDA_PROFILES)
    if(K_PROFILE IN_LIST Profiles)
        message(FATAL_ERROR "Duplicate CUDA PROFILE ${K_PROFILE}; profiles must isolate symbols.")
    endif()
    set_property(GLOBAL APPEND PROPERTY ARDA_CUDA_PROFILES "${K_PROFILE}")
    if(NOT K_ARCHITECTURES)
        set(K_ARCHITECTURES ${ARDASHIR_CUDA_ARCHITECTURES})
    endif()
    set(Architectures)
    set(ManifestTargets)
    foreach(Arch IN LISTS K_ARCHITECTURES)
        if(NOT Arch MATCHES "^([0-9]+)([af]?)(-real)?$")
            message(FATAL_ERROR "CUDA target '${Arch}' must be an explicit native architecture, e.g. 80, 90a or 120-real. PTX, native and all targets are excluded.")
        endif()
        set(Capability "${CMAKE_MATCH_1}")
        set(Suffix "${CMAKE_MATCH_2}")
        set(Exact false)
        if(Suffix)
            set(Exact true)
        endif()
        list(APPEND Architectures "${Capability}${Suffix}-real")
        string(APPEND ManifestTargets "{${Capability}, ${Exact}},")
    endforeach()
    if(NOT Architectures)
        message(FATAL_ERROR "CUDA kernel target requires at least one native architecture.")
    endif()
    # Do not allow a profile to silently override the generated architecture/native-code contract.
    foreach(Option IN LISTS K_OPTIONS K_DEFINITIONS)
        if(Option MATCHES "(gencode|generate-code|gpu-architecture|gpu-code|^-arch|^-code|--ptx|^-ptx|--fatbin|--cubin|--options-file|^-optf|use_fast_math|ARDA_CUDA_BUILD)")
            message(FATAL_ERROR "CUDA option '${Option}' conflicts with the build manifest; use ARCHITECTURES instead.")
        endif()
    endforeach()
    set(FastMath false)
    if(K_FAST_MATH)
        set(FastMath true)
        list(APPEND K_OPTIONS --use_fast_math)
    endif()
    set(Fingerprint "${K_PROFILE};${Architectures};${K_OPTIONS};${K_DEFINITIONS};${CMAKE_CUDA_COMPILER_VERSION}")
    foreach(Source IN LISTS K_SOURCES K_DEPENDS)
        get_filename_component(AbsoluteSource "${Source}" ABSOLUTE)
        file(SHA256 "${AbsoluteSource}" SourceHash)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${AbsoluteSource}")
        string(APPEND Fingerprint ";${SourceHash}")
    endforeach()
    string(SHA256 BuildIdentity "${Fingerprint}")
    set(GeneratedDir "${CMAKE_CURRENT_BINARY_DIR}/${Target}-generated")
    file(MAKE_DIRECTORY "${GeneratedDir}")
    file(WRITE "${GeneratedDir}/ArdaCudaBuildInfo.h"
        "#pragma once\n#include \"Compute/ArdaCudaKernelVariants.h\"\nnamespace arda_cuda_${K_PROFILE} { inline arda::FArdaCudaBuildInfo GetBuildInfo() { return {\"${K_PROFILE}\", \"${BuildIdentity}\", {${ManifestTargets}}, ${FastMath}}; } }\n#define ARDA_CUDA_BUILD_NAMESPACE arda_cuda_${K_PROFILE}\n")
    add_library(${Target} STATIC ${K_SOURCES})
    target_link_libraries(${Target} PRIVATE Ardashir::ArdaBackend CUDA::cudart_static)
    target_include_directories(${Target} PRIVATE "${GeneratedDir}")
    target_compile_definitions(${Target} PRIVATE ${K_DEFINITIONS})
    foreach(Option IN LISTS K_OPTIONS)
        target_compile_options(${Target} PRIVATE "$<$<COMPILE_LANGUAGE:CUDA>:${Option}>")
    endforeach()
    set_target_properties(${Target} PROPERTIES CUDA_STANDARD 17 CUDA_STANDARD_REQUIRED ON
        CUDA_ARCHITECTURES "${Architectures}" CUDA_RUNTIME_LIBRARY Static
        CUDA_SEPARABLE_COMPILATION ON CUDA_RESOLVE_DEVICE_SYMBOLS ON POSITION_INDEPENDENT_CODE ON)
endfunction()
