include_guard(GLOBAL)

# Keep ownership visible in the source tree. Compatibility folders and flat RHI
# headers must not silently reappear when new backend code is added.
function(ardashir_validate_backend_layout BackendRoot)
    set(ArdaRhiModules Context Device Providers Resources CUDA Pipelines Shaders
        Memory Interop Scheduling Config)
    foreach(Visibility Public Private)
        file(GLOB ArdaBackendRootEntries CONFIGURE_DEPENDS
            RELATIVE "${BackendRoot}/${Visibility}" "${BackendRoot}/${Visibility}/*")
        foreach(Entry IN LISTS ArdaBackendRootEntries)
            if(Entry STREQUAL "RHI" OR Entry STREQUAL "FileOperations")
                continue()
            endif()
            if(Visibility STREQUAL "Public" AND Entry STREQUAL "ArdaBackend.h")
                continue()
            endif()
            message(FATAL_ERROR "Unexpected backend root entry: ${Visibility}/${Entry}")
        endforeach()
        file(GLOB ArdaBackendRhiEntries CONFIGURE_DEPENDS
            RELATIVE "${BackendRoot}/${Visibility}/RHI" "${BackendRoot}/${Visibility}/RHI/*")
        foreach(Entry IN LISTS ArdaBackendRhiEntries)
            if(NOT Entry IN_LIST ArdaRhiModules OR NOT IS_DIRECTORY "${BackendRoot}/${Visibility}/RHI/${Entry}")
                message(FATAL_ERROR "Unexpected RHI entry: ${Visibility}/RHI/${Entry}")
            endif()
        endforeach()
        file(GLOB_RECURSE ArdaBackendFiles CONFIGURE_DEPENDS
            RELATIVE "${BackendRoot}/${Visibility}" "${BackendRoot}/${Visibility}/*")
        foreach(BackendFile IN LISTS ArdaBackendFiles)
            if(Visibility STREQUAL "Public" AND BackendFile STREQUAL "ArdaBackend.h")
                continue()
            endif()
            if(BackendFile MATCHES "^FileOperations/[^/]+\\.(h|cpp)$")
                continue()
            endif()
            if(BackendFile MATCHES "^RHI/([^/]+)/[^/]+\\.(h|cpp|cuh)$")
                if(CMAKE_MATCH_1 IN_LIST ArdaRhiModules)
                    continue()
                endif()
            endif()
            message(FATAL_ERROR "Backend file has no owning module: ${Visibility}/${BackendFile}")
        endforeach()
    endforeach()
endfunction()
