if(NOT DEFINED ARDASHIR_SOURCE_DIR)
    message(FATAL_ERROR "ARDASHIR_SOURCE_DIR is required")
endif()

file(GLOB_RECURSE ARDASHIR_BOUNDARY_FILES
    LIST_DIRECTORIES FALSE
    "${ARDASHIR_SOURCE_DIR}/*.h"
    "${ARDASHIR_SOURCE_DIR}/*.hpp"
    "${ARDASHIR_SOURCE_DIR}/*.cpp"
)

set(ARDASHIR_BOUNDARY_VIOLATIONS)
foreach(ARDASHIR_BOUNDARY_FILE IN LISTS ARDASHIR_BOUNDARY_FILES)
    file(TO_CMAKE_PATH "${ARDASHIR_BOUNDARY_FILE}" ARDASHIR_BOUNDARY_PATH)
    if(ARDASHIR_BOUNDARY_PATH MATCHES "/ArdaBackend/Private/" OR
       ARDASHIR_BOUNDARY_PATH MATCHES "/Tests/" OR
       ARDASHIR_BOUNDARY_PATH MATCHES "/ArdaTests/")
        continue()
    endif()

    file(READ "${ARDASHIR_BOUNDARY_FILE}" ARDASHIR_BOUNDARY_CONTENT)
    string(TOLOWER "${ARDASHIR_BOUNDARY_CONTENT}" ARDASHIR_BOUNDARY_CONTENT_LOWER)
    if(ARDASHIR_BOUNDARY_CONTENT_LOWER MATCHES "nvrhi")
        list(APPEND ARDASHIR_BOUNDARY_VIOLATIONS "${ARDASHIR_BOUNDARY_PATH}")
    endif()
endforeach()

if(ARDASHIR_BOUNDARY_VIOLATIONS)
    list(JOIN ARDASHIR_BOUNDARY_VIOLATIONS "\n  " ARDASHIR_BOUNDARY_REPORT)
    message(FATAL_ERROR
        "Opaque RHI source boundary violated outside ArdaBackend/Private:\n"
        "  ${ARDASHIR_BOUNDARY_REPORT}")
endif()
